(** * LDRT_0RB0LB_0RC0LA_1RD1RC_1LA1LD: machine 0RB0LB_0RC0LA_1RD1RC_1LA1LD, boarded by the STAGE-B LADDER at the INSTRUCTION level
    ([NeverQuasiHaltsTr], through [LadderCheckTr]).

    GENERATED by tools/ladder/emit_ladder.py from a `valfam.close`
    certificate -- an UNTRUSTED prover.  Every line below is re-run by the
    Coq kernel: [check_ladder] validates the ladder rules against the rules
    before them, [check_arm] replays every arm, and both are closed by
    [vm_compute].  A wrong chain makes the replay return [None] and this
    file fails to compile.

    The certificate's four PARAMETERS -- the fill law per phase with the
    phase it lands in, the terminator of each phase, the counter's code and
    its step per anchor visit -- arrive as fields of a [LadderFam.Fam]
    value, not as definitions in the kernel (LADDER_PLAN.md 4f).

    Axiom footprint: [functional_extensionality_dep], via [CTape.lift]. *)
From Coq Require Import Arith Lia Bool List.
From BBB4 Require Import BBB4_Statement CTape.
From BBB4.Census Require Import TNF_QH.
From BBB4.Counters Require Import WTape LapGlueQuiet.
From BBB4.Checkers Require Import LapDecider LapAvoid LadderKernel LadderFam.
From BBB4.Checkers Require Import LadderCheck.
From BBB4 Require Import BBBT4_Statement.
From BBB4.Checkers Require Import WrapTr LadderCheckTr.
From BBB4.Counters Require Import LapGlueTr.
From BBB4.Checkers Require Import LadderCheckLiftTr.
From BBB4.Checkers Require Import LadderNest LadderCheckNestTr.
Import ListNotations.

Definition mk_0RB0LB_0RC0LA_1RD1RC_1LA1LD (w : Sym) (d : Dir) (n : St) : option Trans :=
  Some (mkTrans w d n).
Local Notation mk := mk_0RB0LB_0RC0LA_1RD1RC_1LA1LD.

(** 0RB0LB_0RC0LA_1RD1RC_1LA1LD *)
Definition tm_0RB0LB_0RC0LA_1RD1RC_1LA1LD : TM := fun q s => match q, s with
  | StA, S0 => mk S0 DR StB
  | StA, S1 => mk S0 DL StB
  | StB, S0 => mk S0 DR StC
  | StB, S1 => mk S0 DL StA
  | StC, S0 => mk S1 DR StD
  | StC, S1 => mk S1 DR StC
  | StD, S0 => mk S1 DL StA
  | StD, S1 => mk S1 DL StD
  end.
(** the instructions the machine never fires; the whole board runs
    on the machine wrapped at them, where firing one halts *)
Definition pins_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list Instr := [].
Local Notation tm := (tm_wrap_trs tm_0RB0LB_0RC0LA_1RD1RC_1LA1LD pins_0RB0LB_0RC0LA_1RD1RC_1LA1LD).

(** ** The family, as DATA

    The successor is a PARAMETER here, not a law: [fam_succ] reads the fill
    of the phase it is in, the code the digits are written in, and the step
    the counter advances by, all off this record. *)
Definition fam_0RB0LB_0RC0LA_1RD1RC_1LA1LD : Fam := mkFam 2 [[S0;S0];[S1;S0]] [] [[S1]] Binary 1 [mkFill 1 [] 0 [] 0] StC S0 false [].
Local Notation FAM := fam_0RB0LB_0RC0LA_1RD1RC_1LA1LD.

(** ** The ladder, as DATA

    4 window rule(s).  [check_ladder] validates rule i against rules
    0..i-1 only, and [rule_sound] -- ONE theorem, by induction on ladder
    POSITION -- turns that into soundness for all of them. *)
Definition lad_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list (LRule * list rstep) :=
  [(mkLRule (mkC StD (mkS [S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) (mkC StD (mkS [] [] 0 0 []) S1 (mkS [S1] [] 0 0 [])) 0 1, [RB (SWin 1)]);
   (mkLRule (mkC StC (mkS [] [] 0 0 []) S1 (mkS [S1] [] 0 0 [])) (mkC StC (mkS [S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) 0 1, [RB (SWin 1)]);
   (mkLRule (mkC StB (mkS [S1;S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S0] [] 0 0 [])) 0 2, [RB (SWin 2)]);
   (mkLRule (mkC StB (mkS [S1;S1;S1;S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S0;S0;S0] [] 0 0 [])) 0 4, [RB (SWin 4)])].
Local Notation lad := lad_0RB0LB_0RC0LA_1RD1RC_1LA1LD.

Definition rules_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list LRule := map fst lad.
Local Notation rules := rules_0RB0LB_0RC0LA_1RD1RC_1LA1LD.

Lemma ladder_ok_0RB0LB_0RC0LA_1RD1RC_1LA1LD : check_ladder tm [] lad = true.
Proof. vm_compute. reflexivity. Qed.

Lemma rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD : Forall (RuleSound tm false false) rules.
Proof. apply rule_sound_nil. exact ladder_ok_0RB0LB_0RC0LA_1RD1RC_1LA1LD. Qed.

(** ** The arms, as DATA

    Each is a rule the kernel re-derives from the machine.  [el]/[er] record
    whether that side's tail is known empty: the fill arm must see the end
    of the counter, the interior arms hold against an arbitrary tail. *)
(* C[0] L<> R<0^2+y0 1^1>  ==>  C[0] L<> R<1^1 0^1+y0 1^1>   [4 steps] *)
Definition arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0] [S0] 1 0 [S1]))
          (mkC StC (mkS [S0] [] 0 0 []) S0 (mkS [S1;S0] [S0] 1 0 [S1])) 0 4.
Definition ch_arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 2)].
Lemma ok_arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true true rules arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true true arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* arm110: NO KERNEL CHAIN -- step count 0*j+212, certificate claims 0*j+142 *)
(* arm134: NO KERNEL CHAIN -- step count 0*j+256, certificate claims 0*j+160 *)
(* arm162: NO KERNEL CHAIN -- step count 0*j+304, certificate claims 0*j+178 *)
(* C[0] L<> R<10^1 1^1>  ==>  C[0] L<> R<0^4 1^1>   [32 steps] *)
Definition arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S1] [] 0 0 []))
          (mkC StC (mkS [S0;S0] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1] [] 0 0 [])) 0 32.
Definition ch_arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 21);RB (SWinR 9)].
Lemma ok_arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true true rules arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true true arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm30_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* C[0] L<> R<10^2 1^1>  ==>  C[0] L<> R<0^6 1^1>   [52 steps] *)
Definition arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StC (mkS [S0;S0] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 52.
Definition ch_arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 39);RB (SWinR 11)].
Lemma ok_arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true true rules arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true true arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm37_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* arm46: NO KERNEL CHAIN -- step count 0*j+76, certificate claims 0*j+70 *)
(* arm59: NO KERNEL CHAIN -- step count 0*j+104, certificate claims 0*j+88 *)
(* arm74: NO KERNEL CHAIN -- step count 0*j+136, certificate claims 0*j+106 *)
(* arm90: NO KERNEL CHAIN -- step count 0*j+172, certificate claims 0*j+124 *)
(* C[0] L<> R<0^2+y0 10^1+y1 1^1>  ==>  C[0] L<> R<1^1 0^1+y0 10^1+y1 1^1>   [4 steps] *)
Definition arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [] 0 0 []))
          (mkC StC (mkS [S0] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 2)].
Lemma ok_arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true false rules arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true false arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm17_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* C[0] L<> R<0^2+y0 10^1+y1 0^2+y2 1^1>  ==>  C[0] L<> R<1^1 0^1+y0 10^1+y1 0^2+y2 1^1>   [4 steps] *)
Definition arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [] 0 0 []))
          (mkC StC (mkS [S0] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 2)].
Lemma ok_arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true false rules arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true false arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm18_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* C[0] L<> R<10^1 0^2+y0 #^1>  ==>  C[0] L<> R<0^2 1^1 0^1+y0 #^1>   [16 steps] *)
Definition arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S0] [] 0 0 []))
          (mkC StC (mkS [S0;S0] [] 0 0 []) S0 (mkS [S0;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true false rules arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true false arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm31_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* C[0] L<> R<10^2 0^2+y0 #^1>  ==>  C[0] L<> R<0^4 1^1 0^1+y0 #^1>   [32 steps] *)
Definition arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S1;S0;S0] [] 0 0 []))
          (mkC StC (mkS [S0;S0] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1] [] 0 0 [])) 0 32.
Definition ch_arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 30)].
Lemma ok_arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true false rules arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true false arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm48_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* C[0] L<> R<10^3 0^2+y0 #^1>  ==>  C[0] L<> R<0^6 1^1 0^1+y0 #^1>   [52 steps] *)
Definition arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S1;S0;S1;S0;S0] [] 0 0 []))
          (mkC StC (mkS [S0;S0] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 52.
Definition ch_arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 50)].
Lemma ok_arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true false rules arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true false arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm62_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(* arm102: NO KERNEL CHAIN -- step count 0*j+136, certificate claims 0*j+88 *)
(* arm114: NO KERNEL CHAIN -- step count 0*j+76, certificate claims 0*j+70 *)
(* arm118: NO KERNEL CHAIN -- step count 0*j+104, certificate claims 0*j+74 *)
(* arm122: NO KERNEL CHAIN -- step count 0*j+136, certificate claims 0*j+88 *)
(* arm126: NO KERNEL CHAIN -- step count 0*j+172, certificate claims 0*j+102 *)
(* arm138: NO KERNEL CHAIN -- step count 0*j+76, certificate claims 0*j+70 *)
(* arm142: NO KERNEL CHAIN -- step count 0*j+104, certificate claims 0*j+88 *)
(* arm146: NO KERNEL CHAIN -- step count 0*j+136, certificate claims 0*j+88 *)
(* arm150: NO KERNEL CHAIN -- step count 0*j+172, certificate claims 0*j+102 *)
(* arm154: NO KERNEL CHAIN -- step count 0*j+212, certificate claims 0*j+116 *)
(* arm66: NO KERNEL CHAIN -- step count 0*j+76, certificate claims 0*j+60 *)
(* arm78: NO KERNEL CHAIN -- step count 0*j+76, certificate claims 0*j+60 *)
(* arm82: NO KERNEL CHAIN -- step count 0*j+104, certificate claims 0*j+74 *)
(* arm94: NO KERNEL CHAIN -- step count 0*j+76, certificate claims 0*j+60 *)
(* arm98: NO KERNEL CHAIN -- step count 0*j+104, certificate claims 0*j+74 *)
(* C[0] L<> R<0^2+y0 10^1+y1 0^2+y2 10^1+y3 #^1>  ==>  C[0] L<> R<1^1 0^1+y0 10^1+y1 0^2+y2 10^1+y3 #^1>   [4 steps] *)
Definition arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [] 0 0 []))
          (mkC StC (mkS [S0] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list rstep := [RB (SWin 2);RB (SWinL 2)].
Lemma ok_arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_arm tm true false rules arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD : RuleSound tm true false arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof. eapply arm_sound; [exact rules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_arm15_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. Qed.

(** ** What this board establishes

    9 of 31 arms of the certificate are re-derived by the kernel and
    sound: each [sound_*] is a theorem that the machine, from that arm's
    left-hand side and against any tail the flags permit, reaches the arm's
    right-hand side in exactly the certificate's step count. *)

(** ** The closure: from the RULES to [NeverQuasiHaltsSt]

    The arms below are the case split of [LadderCheck.digs_decomp], built
    from the FAMILY rather than mined: interior arms for the digits below the
    top, and fill arms.  Every certificate arm above is one of these with its
    run lengths pinned to their lower bounds, which is why 31 of them
    collapse to 4 here.

    Both classes are indexed by [LadderCheck]'s ONE arm scheme -- flat below
    a threshold, residue-and-stride at or above it.  The interior class runs
    at threshold 2 stride 1, the fill class at threshold 1
    stride 1.

    [board_neverqh] consumes them, the boot, and one chain per state per fill
    arm, and returns the machine-level theorem. *)

(** *** The inner rules: what the nested arms iterate

    4 rule(s), validated like the ladder at both tails opaque. *)
Definition nlad_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list (LRule * list rstep) :=
  [(mkLRule (mkC StB (mkS [S0] [] 0 0 []) S0 (mkS [S1;S1] [S1] 2 0 [S0;S1])) (mkC StB (mkS [S0] [] 0 0 []) S0 (mkS [S1;S1] [S1] 2 2 [])) 4 12, [RB (SWin 2);RB (SCycR 1);RB (SWin 4);RB (SCycL 1 0);RB (SWin 6);RB (SRotR 1);RB (SRotR 1);RB (SFoldR 2)]);
   (mkLRule (mkC StA (mkS [S1;S1] [S1] 2 2 [S0]) S1 (mkS [] [] 0 0 [])) (mkC StA (mkS [] [S1] 2 2 [S0]) S1 (mkS [S0;S0] [] 0 0 [])) 0 2, [RB (SWin 2)]);
   (mkLRule (mkC StB (mkS [S0] [] 0 0 []) S0 (mkS [S1;S1] [S1] 2 0 [S0;S1])) (mkC StB (mkS [S0] [] 0 0 []) S0 (mkS [S1;S1] [S1] 2 2 [])) 4 12, [RB (SWin 2);RB (SCycR 1);RB (SWin 4);RB (SCycL 1 0);RB (SWin 6);RB (SRotR 1);RB (SRotR 1);RB (SFoldR 2)]);
   (mkLRule (mkC StA (mkS [S1;S1] [S1] 2 2 [S0]) S1 (mkS [] [] 0 0 [])) (mkC StA (mkS [] [S1] 2 2 [S0]) S1 (mkS [S0;S0] [] 0 0 [])) 0 2, [RB (SWin 2)])].
Definition nrules_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list LRule := map fst nlad_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Local Notation nrules := nrules_0RB0LB_0RC0LA_1RD1RC_1LA1LD.

Lemma nladder_ok_0RB0LB_0RC0LA_1RD1RC_1LA1LD : check_ladder tm [] nlad_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Lemma nrules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD : Forall (RuleSound tm false false) nrules.
Proof. apply rule_sound_nil. exact nladder_ok_0RB0LB_0RC0LA_1RD1RC_1LA1LD. Qed.

Definition iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0] [] 0 0 [])) 0 1.
Definition ch_iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list nseg :=
  [NCh [RB (SWin 2);RB (SWinL 2)]].
Lemma ok_iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_narm tm true false nrules iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S1;S0] [] 0 0 [])) 0 1.
Definition ch_iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list nseg :=
  [NCh [RB (SWin 2);RB (SWinL 14)]].
Lemma ok_iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_narm tm true false nrules iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0;S1;S0] [S1;S0] 1 0 [S0;S0]))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0] [S0;S0] 1 0 [S1;S0])) 0 1.
Definition ch_iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list nseg :=
  [NCh [RB (SWin 2);RB (SWinL 5);RB (SUnrotR 1)];
   NUp 0 [] [S0;S1] 0 1 0 (mkS [] [] 0 0 []) (mkS [S0;S0;S0] [] 0 0 []) true;
   NCh [RB (SWin 2);RB (SCycR 1);RB (SWin 3);RB (SRotL 1)];
   NDn 1 [] [S0;S0] 0 1 0 (mkS [S0] [] 0 0 []) (mkS [S1;S0] [] 0 0 []) true;
   NCh [RB (SWin 4)]].
Lemma ok_iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_narm tm true false nrules iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0] [S1;S0] 1 0 [S1]))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0] [S0;S0] 1 0 [S0;S0;S1])) 0 1.
Definition ch_farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD : list nseg :=
  [NCh [RB (SWin 2);RB (SWinL 5);RB (SRotR 1)];
   NUp 2 [] [S0;S1] 0 1 0 (mkS [] [] 0 0 []) (mkS [] [] 0 0 []) true;
   NCh [RB (SWin 2);RB (SCycR 1);RB (SWinR 3);RB (SRotL 1)];
   NDn 3 [] [S0;S0] 0 1 0 (mkS [S0] [] 0 0 []) (mkS [S1] [] 0 0 []) true;
   NCh [RB (SWin 4);RB (SUnrotR 2)]].
Lemma ok_farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  check_narm tm true true nrules farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD ch_farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm_0RB0LB_0RC0LA_1RD1RC_1LA1LD (d r : nat) : LRule :=
  match d, r with
  | 0, 0 => iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD
  | 0, 1 => iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD
  | 0, 2 => iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD
  | _, _ => iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD   (* unreachable: only d < b-1 and r < N0 + st *)
  end.

(** The fill arms, one per arm index and PHASE.  Both tails are known
    empty -- they are the only arms that see the end of the counter -- and
    the arm at index [r] has [r] guaranteed block copies materialised into
    [s_pre], without which it has no chain at all.  [fm1]/[fm2] say how the
    fill target's own guaranteed copies divide about the block.

    The phase is the second index because the fill arm is the ONLY one that
    sees a terminator: it leaves from the terminator of its own phase and
    lands on the terminator of the phase its law names.  The interior arms
    keep the terminator in the opaque tail and are phase-free. *)
Definition farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD (r ph : nat) : LRule :=
  match r, ph with
  | 1, 0 => farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD
  | _, _ => farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD  (* unreachable: 0 < r < N0 + st *)
  end.

Definition fm1_0RB0LB_0RC0LA_1RD1RC_1LA1LD (r ph : nat) : nat :=
  match r, ph with | 1, 0 => 1 | _, _ => 0 end.
Definition fm2_0RB0LB_0RC0LA_1RD1RC_1LA1LD (r ph : nat) : nat :=
  match r, ph with | 1, 0 => 1 | _, _ => 0 end.

(** One chain per UNPINNED INSTRUCTION per fill arm, at the VISIT PHASE
    0.  [fire_of_run_instr] turns each into a fire of that instruction,
    and [tops_cofinal_at] says the tops of that phase keep coming.  The fill
    arm is the counter's overflow, so this is where the rare instruction of
    a sparse row is witnessed. *)
Definition vis_0RB0LB_0RC0LA_1RD1RC_1LA1LD (r : nat) (t : Instr) : list lstep :=
  match r, t with
  | 1, (StA, S0) => [SWinL 4]
  | 1, (StA, S1) => [SWin 2;SCycR 1;SWinR 3]
  | 1, (StB, S0) => [SWinL 7]
  | 1, (StB, S1) => [SWinL 5]
  | 1, (StC, S0) => [SWin 0]
  | 1, (StC, S1) => [SWinL 8]
  | 1, (StD, S0) => [SWinL 3]
  | 1, (StD, S1) => [SWin 1]
  | _, _ => []
  end.

(** ...each after its segment program: a visit that fires past the rounds
    of a nested fill arm first runs that arm's program up to them. *)
Definition vsegs_0RB0LB_0RC0LA_1RD1RC_1LA1LD (r : nat) (t : Instr) : list nseg :=
  match r, t with
  | 1, (StA, S0) => []
  | 1, (StA, S1) => [NCh [RB (SWin 2);RB (SWinL 5);RB (SRotR 1)]; NUp 2 [] [S0;S1] 0 1 0 (mkS [] [] 0 0 []) (mkS [] [] 0 0 []) true]
  | 1, (StB, S0) => []
  | 1, (StB, S1) => []
  | 1, (StC, S0) => []
  | 1, (StC, S1) => []
  | 1, (StD, S0) => []
  | 1, (StD, S1) => []
  | _, _ => []
  end.

Lemma iarm_reach_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall d r,
  d < fm_b FAM - 1 -> r < 2 + 1 ->
  ReachL tm (negb (fm_left FAM)) (fm_left FAM)
    (lr_lhs (iarm_0RB0LB_0RC0LA_1RD1RC_1LA1LD d r)) (lr_rhs (iarm_0RB0LB_0RC0LA_1RD1RC_1LA1LD d r)).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_iarm0_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. }
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_iarm0_1_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. }
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_iarm0_2_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_lhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall d r,
  d < fm_b FAM - 1 -> r < 2 + 1 ->
  lr_lhs (iarm_0RB0LB_0RC0LA_1RD1RC_1LA1LD d r)
    = cls_conf FAM (cls_side FAM [] (fm_b FAM - 1) r
                      (astride 2 1 r) [d]).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_rhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall d r,
  d < fm_b FAM - 1 -> r < 2 + 1 ->
  lr_rhs (iarm_0RB0LB_0RC0LA_1RD1RC_1LA1LD d r)
    = cls_conf FAM (cls_side FAM [] 0 r (astride 2 1 r) [S d]).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma farm_reach_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall r ph, 0 < r -> r < 1 + 1 ->
  ph < 1 ->
  ReachL tm true true (lr_lhs (farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph)) (lr_rhs (farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph)).
Proof.
  intros r ph H0 Hr Hph.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  {
    destruct ph as [|ph].
    { eapply narm_reach; [exact nrules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD | exact ok_farm1_0_0RB0LB_0RC0LA_1RD1RC_1LA1LD]. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma farm_lhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall r ph, 0 < r -> r < 1 + 1 ->
  ph < 1 ->
  lr_lhs (farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph)
    = cls_conf FAM (run_side FAM (fm_b FAM - 1) r (astride 1 1 r)
                      0 ph [] []).
Proof.
  intros r ph H0 Hr Hph.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  {
    destruct ph as [|ph].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma farm_rhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall r ph, 0 < r -> r < 1 + 1 ->
  ph < 1 ->
  lr_rhs (farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph)
    = cls_conf FAM (run_side FAM (f_mid (fam_fill FAM ph)) (fm1_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph)
                      (astride 1 1 r) (fm2_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph)
                      (f_to (fam_fill FAM ph))
                      (f_pre (fam_fill FAM ph)) (f_suf (fam_fill FAM ph))).
Proof.
  intros r ph H0 Hr Hph.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  {
    destruct ph as [|ph].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma fm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall r ph, 0 < r -> r < 1 + 1 ->
  ph < 1 ->
  fm1_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph + fm2_0RB0LB_0RC0LA_1RD1RC_1LA1LD r ph
  + (length (f_pre (fam_fill FAM ph)) + length (f_suf (fam_fill FAM ph)))
  = r + f_s (fam_fill FAM ph).
Proof.
  intros r ph H0 Hr Hph.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  {
    destruct ph as [|ph].
    { vm_compute; lia. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma vis_ok_0RB0LB_0RC0LA_1RD1RC_1LA1LD : forall r t, ~ In t pins_0RB0LB_0RC0LA_1RD1RC_1LA1LD -> 0 < r ->
  r < 1 + 1 ->
  nfire tm true true nrules (vsegs_0RB0LB_0RC0LA_1RD1RC_1LA1LD r t) (vis_0RB0LB_0RC0LA_1RD1RC_1LA1LD r t)
    (lr_lhs (farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD r 0)) = Some t.
Proof.
  intros r t Hnp H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { destruct t as [q s]; destruct q, s; try (exfalso; apply Hnp; simpl; tauto); vm_compute; reflexivity. }
  exfalso; lia.
Qed.

Lemma bootl_0RB0LB_0RC0LA_1RD1RC_1LA1LD :
  stepn tm 22 InitES = Some (lift (fam_cfg FAM ([0], 0, 0))).
Proof.
  assert (H : match csteps tm 22 c0 with
              | Some c => ceqb c (fam_cfg FAM ([0], 0, 0))
              | None => false end = true) by (vm_compute; reflexivity).
  destruct (csteps tm 22 c0) as [c|] eqn:E; [|discriminate].
  rewrite <- lift_c0, (csteps_lift _ _ _ _ E). f_equal. apply ceqb_lift. exact H.
Qed.

(** The machine-level theorem, at the INSTRUCTION level, through the nested
    board [LadderCheckNestTr.boardN_neverqhtr]. *)
Theorem nqhtr_0RB0LB_0RC0LA_1RD1RC_1LA1LD : NeverQuasiHaltsTr tm_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Proof.
  eapply (boardN_neverqhtr tm_0RB0LB_0RC0LA_1RD1RC_1LA1LD pins_0RB0LB_0RC0LA_1RD1RC_1LA1LD FAM 1
                           iarm_0RB0LB_0RC0LA_1RD1RC_1LA1LD 2 1
                           farm_0RB0LB_0RC0LA_1RD1RC_1LA1LD 1 1
                           fm1_0RB0LB_0RC0LA_1RD1RC_1LA1LD fm2_0RB0LB_0RC0LA_1RD1RC_1LA1LD 0
                           nrules vsegs_0RB0LB_0RC0LA_1RD1RC_1LA1LD vis_0RB0LB_0RC0LA_1RD1RC_1LA1LD
                           [0] 0).
  - vm_compute; lia.
  - vm_compute; reflexivity.
  - vm_compute; reflexivity.
  - intros ph Hph.
    destruct ph as [|ph].
    { vm_compute; repeat constructor. }
    exfalso; lia.
  - intros ph Hph.
    destruct ph as [|ph].
    { vm_compute; repeat constructor. }
    exfalso; lia.
  - intros ph Hph.
    destruct ph as [|ph].
    { vm_compute; lia. }
    exfalso; lia.
  - intros ph Hph.
    destruct ph as [|ph].
    { vm_compute; lia. }
    exfalso; lia.
  - intros ph Hph.
    destruct ph as [|ph].
    { vm_compute; lia. }
    exfalso; lia.
  - lia.
  - intros ph Hph.
    destruct ph as [|ph].
    { exists 0; vm_compute; reflexivity. }
    exfalso; lia.
  - exact fm12_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - repeat constructor.
  - vm_compute; lia.
  - lia.
  - lia.
  - exact iarm_reach_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact iarm_lhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact iarm_rhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - lia.
  - lia.
  - exact farm_reach_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact farm_lhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact farm_rhs_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact nrules_sound_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact vis_ok_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
  - exact bootl_0RB0LB_0RC0LA_1RD1RC_1LA1LD.
Qed.
