(** * LDRT_1RB1LC_0LA1RA_0RB0LD_0RA1LD: machine 1RB1LC_0LA1RA_0RB0LD_0RA1LD, boarded by the STAGE-B LADDER at the INSTRUCTION level
    ([NeverQuasiHaltsTr], through [LadderCheckTr]).

    GENERATED by tools/ladder/emit_ladder.py from a `valfam.close`
    certificate -- an UNTRUSTED prover.  Every line below is re-run by the
    Coq kernel: [check_ladder] validates the ladder rules against the rules
    before them, [check_arm] replays every arm, and both are closed by
    [vm_compute].  A wrong chain makes the replay return [None] and this
    file fails to compile.

    The certificate's four PARAMETERS -- the fill law per phase with the
    phase it lands in, the terminator of each phase, the counter's code and
    its step per anchor visit -- arrive as fields of a [LadderFam.Fam]
    value, not as definitions in the kernel (LADDER_PLAN.md 4f).

    Axiom footprint: [functional_extensionality_dep], via [CTape.lift]. *)
From Coq Require Import Arith Lia Bool List.
From BBB4 Require Import BBB4_Statement CTape.
From BBB4.Census Require Import TNF_QH.
From BBB4.Counters Require Import WTape LapGlueQuiet.
From BBB4.Checkers Require Import LapDecider LapAvoid LadderKernel LadderFam.
From BBB4.Checkers Require Import LadderCheck.
From BBB4 Require Import BBBT4_Statement.
From BBB4.Checkers Require Import WrapTr LadderCheckTr.
From BBB4.Counters Require Import LapGlueTr.
From BBB4.Checkers Require Import LadderCheckLiftTr.
From BBB4.Checkers Require Import LadderNest LadderCheckNestTr.
Import ListNotations.

Definition mk_1RB1LC_0LA1RA_0RB0LD_0RA1LD (w : Sym) (d : Dir) (n : St) : option Trans :=
  Some (mkTrans w d n).
Local Notation mk := mk_1RB1LC_0LA1RA_0RB0LD_0RA1LD.

(** 1RB1LC_0LA1RA_0RB0LD_0RA1LD *)
Definition tm_1RB1LC_0LA1RA_0RB0LD_0RA1LD : TM := fun q s => match q, s with
  | StA, S0 => mk S1 DR StB
  | StA, S1 => mk S1 DL StC
  | StB, S0 => mk S0 DL StA
  | StB, S1 => mk S1 DR StA
  | StC, S0 => mk S0 DR StB
  | StC, S1 => mk S0 DL StD
  | StD, S0 => mk S0 DR StA
  | StD, S1 => mk S1 DL StD
  end.
(** the instructions the machine never fires; the whole board runs
    on the machine wrapped at them, where firing one halts *)
Definition pins_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list Instr := [].
Local Notation tm := (tm_wrap_trs tm_1RB1LC_0LA1RA_0RB0LD_0RA1LD pins_1RB1LC_0LA1RA_0RB0LD_0RA1LD).

(** ** The family, as DATA

    The successor is a PARAMETER here, not a law: [fam_succ] reads the fill
    of the phase it is in, the code the digits are written in, and the step
    the counter advances by, all off this record. *)
Definition fam_1RB1LC_0LA1RA_0RB0LD_0RA1LD : Fam := mkFam 2 [[S1];[S0]] [] [[S1;S0;S1]] Binary 1 [mkFill 1 [] 0 [] 0] StB S1 false [].
Local Notation FAM := fam_1RB1LC_0LA1RA_0RB0LD_0RA1LD.

(** ** The ladder, as DATA

    2 window rule(s).  [check_ladder] validates rule i against rules
    0..i-1 only, and [rule_sound] -- ONE theorem, by induction on ladder
    POSITION -- turns that into soundness for all of them. *)
Definition lad_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list (LRule * list rstep) :=
  [(mkLRule (mkC StD (mkS [S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) (mkC StD (mkS [] [] 0 0 []) S1 (mkS [S1] [] 0 0 [])) 0 1, [RB (SWin 1)]);
   (mkLRule (mkC StA (mkS [] [] 0 0 []) S0 (mkS [S1;S0] [] 0 0 [])) (mkC StA (mkS [S1;S1] [] 0 0 []) S0 (mkS [] [] 0 0 [])) 0 2, [RB (SWin 2)])].
Local Notation lad := lad_1RB1LC_0LA1RA_0RB0LD_0RA1LD.

Definition rules_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list LRule := map fst lad.
Local Notation rules := rules_1RB1LC_0LA1RA_0RB0LD_0RA1LD.

Lemma ladder_ok_1RB1LC_0LA1RA_0RB0LD_0RA1LD : check_ladder tm [] lad = true.
Proof. vm_compute. reflexivity. Qed.

Lemma rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD : Forall (RuleSound tm false false) rules.
Proof. apply rule_sound_nil. exact ladder_ok_1RB1LC_0LA1RA_0RB0LD_0RA1LD. Qed.

(** ** The arms, as DATA

    Each is a rule the kernel re-derives from the machine.  [el]/[er] record
    whether that side's tail is known empty: the fill arm must see the end
    of the counter, the interior arms hold against an arbitrary tail. *)
(* B[1] L<> R<1^2+y0 0^1 1^1>  ==>  B[1] L<> R<0^1 1^1+y0 0^1 1^1>   [12 steps] *)
Definition arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S1] [S1] 1 0 [S0;S1]))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S0;S1] [S1] 1 0 [S0;S1])) 0 12.
Definition ch_arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 10)].
Lemma ok_arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm9_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1+y0 0^1 1^1>  ==>  B[1] L<> R<1^1 0^1 1^y0 0^1 1^1>   [10 steps] *)
Definition arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S1] [S1] 1 0 [S0;S1]))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S0;S1] [S1] 1 0 [S0;S1])) 0 10.
Definition ch_arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 6);RB (SWinL 4)].
Lemma ok_arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm12_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1>   [16 steps] *)
Definition arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 16.
Definition ch_arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 4);RB (SWinR 8);RB (SWinL 4)].
Lemma ok_arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm19_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1+y0 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^y0 0^1 1^1>   [16 steps] *)
Definition arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1] [S1] 1 0 [S0;S1]))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1] [S1] 1 0 [S0;S1])) 0 16.
Definition ch_arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm29_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^1>   [22 steps] *)
Definition arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 22.
Definition ch_arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 7);RB (SWinR 13)].
Lemma ok_arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm24_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1+y0 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^y0 0^1 1^1>   [14 steps] *)
Definition arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1] [S1] 1 0 [S0;S1]))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1] [S1] 1 0 [S0;S1])) 0 14.
Definition ch_arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm39_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^1>   [20 steps] *)
Definition arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 20.
Definition ch_arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 6);RB (SWinR 10);RB (SWinL 4)].
Lemma ok_arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm34_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* arm64: NO KERNEL CHAIN -- no chain found *)
(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1+y0 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^y0 0^1 1^1>   [20 steps] *)
Definition arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1] [S1] 1 0 [S0;S1]))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1] [S1] 1 0 [S0;S1])) 0 20.
Definition ch_arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm49_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^6 0^1 1^1>   [26 steps] *)
Definition arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 26.
Definition ch_arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 9);RB (SWinR 15)].
Lemma ok_arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm44_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^4 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^3 0^1 1^1>   [18 steps] *)
Definition arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S1;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm119_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^3 0^1 1^1>   [14 steps] *)
Definition arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm124_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^3 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^2 0^1 1^2 0^1 1^1>   [14 steps] *)
Definition arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm134_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^4 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^3 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm154_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^5 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^4 0^1 1^1>   [18 steps] *)
Definition arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S1;S1;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm189_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^4 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^4 0^1 1^1>   [14 steps] *)
Definition arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S1;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm194_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^3 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^2 0^1 1^3 0^1 1^1>   [14 steps] *)
Definition arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S0;S1;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm204_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^4 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^3 0^1 1^2 0^1 1^1>   [14 steps] *)
Definition arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm224_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^5 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^4 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm259_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^7 0^1 1^1>   [24 steps] *)
Definition arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 24.
Definition ch_arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 8);RB (SWinR 12);RB (SWinL 4)].
Lemma ok_arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm59_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^1 0^1 1^1>   [18 steps] *)
Definition arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm69_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm74_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^2 0^1 1^1>   [18 steps] *)
Definition arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm84_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^2 0^1 1^1>   [14 steps] *)
Definition arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm89_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^3 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^2 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm99_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^1 0^1 1^1 0^1 1^1>   [20 steps] *)
Definition arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm104_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm109_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^6 0^1 1^2 0^1 1^1>   [24 steps] *)
Definition arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 24.
Definition ch_arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 22)].
Lemma ok_arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm129_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^2 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^1 0^1 1^2 0^1 1^1>   [20 steps] *)
Definition arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm139_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1>   [16 steps] *)
Definition arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm144_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^3 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^2 0^1 1^1 0^1 1^1>   [20 steps] *)
Definition arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm159_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm164_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^3 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^2 0^1 1^1 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm174_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^4 0^1 1^1>  ==>  B[1] L<> R<1^6 0^1 1^3 0^1 1^1>   [24 steps] *)
Definition arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S0;S1;S1;S1;S0;S1] [] 0 0 [])) 0 24.
Definition ch_arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 22)].
Lemma ok_arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm199_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^2 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^1 0^1 1^3 0^1 1^1>   [20 steps] *)
Definition arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm209_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^1 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^1 0^1 1^3 0^1 1^1>   [16 steps] *)
Definition arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm214_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^3 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^2 0^1 1^2 0^1 1^1>   [20 steps] *)
Definition arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm229_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^2 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^2 0^1 1^2 0^1 1^1>   [16 steps] *)
Definition arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm234_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^3 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^2 0^1 1^1 0^1 1^2 0^1 1^1>   [16 steps] *)
Definition arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm244_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^4 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^3 0^1 1^1 0^1 1^1>   [20 steps] *)
Definition arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm264_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^3 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^3 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm269_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^3 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^2 0^1 1^2 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm279_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^4 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^3 0^1 1^1 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm294_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^8 0^1 1^1>   [30 steps] *)
Definition arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 30.
Definition ch_arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 11);RB (SWinR 17)].
Lemma ok_arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm79_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^6 0^1 1^1 0^1 1^1>   [24 steps] *)
Definition arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 24.
Definition ch_arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 22)].
Lemma ok_arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm94_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^9 0^1 1^1>   [28 steps] *)
Definition arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 28.
Definition ch_arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinR 14);RB (SWinL 4)].
Lemma ok_arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm114_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^7 0^1 1^1 0^1 1^1>   [22 steps] *)
Definition arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 22.
Definition ch_arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 18);RB (SWinL 4)].
Lemma ok_arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm149_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^1 0^1 1^1 0^1 1^1>   [18 steps] *)
Definition arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm169_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm179_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^3 0^1 1^1>  ==>  B[1] L<> R<1^7 0^1 1^2 0^1 1^1>   [22 steps] *)
Definition arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S0;S1;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 22.
Definition ch_arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 18);RB (SWinL 4)].
Lemma ok_arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm219_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^1 0^1 1^2 0^1 1^1>   [18 steps] *)
Definition arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm239_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1>   [14 steps] *)
Definition arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm249_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^3 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^5 0^1 1^2 0^1 1^1 0^1 1^1>   [18 steps] *)
Definition arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 18.
Definition ch_arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 14);RB (SWinL 4)].
Lemma ok_arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm274_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^2 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm284_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^3 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^3 0^1 1^2 0^1 1^1 0^1 1^1 0^1 1^1>   [14 steps] *)
Definition arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 14.
Definition ch_arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 10);RB (SWinL 4)].
Lemma ok_arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm299_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^10 0^1 1^1>   [34 steps] *)
Definition arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 34.
Definition ch_arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 13);RB (SWinR 19)].
Lemma ok_arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm184_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1>  ==>  B[1] L<> R<1^8 0^1 1^1 0^1 1^1>   [28 steps] *)
Definition arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S0;S1;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S1;S0;S1;S0;S1] [] 0 0 [])) 0 28.
Definition ch_arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 26)].
Lemma ok_arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm254_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^6 0^1 1^1 0^1 1^1 0^1 1^1>   [24 steps] *)
Definition arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S0;S1;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 24.
Definition ch_arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 22)].
Lemma ok_arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm289_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^1 0^1 1^2 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^4 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>   [20 steps] *)
Definition arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S0;S1;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 18)].
Lemma ok_arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm304_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<1^1 0^1 1^2 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^2 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>   [16 steps] *)
Definition arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0;S1;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S0;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 2);RB (SWinL 14)].
Lemma ok_arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm309_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* B[1] L<> R<0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1 0^1 1^1>  ==>  B[1] L<> R<1^11 0^1 1^1>   [32 steps] *)
Definition arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1;S0;S1;S0;S1;S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [S0] [] 0 0 []) S1 (mkS [S1;S1;S1;S1;S1;S1;S1;S1;S1;S1;S1;S0;S1;S0] [] 0 0 [])) 0 32.
Definition ch_arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list rstep := [RB (SWin 12);RB (SWinR 16);RB (SWinL 4)].
Lemma ok_arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_arm tm true true rules arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD : RuleSound tm true true arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof. eapply arm_sound; [exact rules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_arm314_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. Qed.

(* arm8: NO KERNEL CHAIN -- no chain found *)
(* arm10: NO KERNEL CHAIN -- no chain found *)
(** ** What this board establishes

    60 of 63 arms of the certificate are re-derived by the kernel and
    sound: each [sound_*] is a theorem that the machine, from that arm's
    left-hand side and against any tail the flags permit, reaches the arm's
    right-hand side in exactly the certificate's step count. *)

(** ** The closure: a ZECKENDORF counter ([LadderCheckZeckTr])

    Weights 1, 2, 3, 5, ..., no two adjacent ones.  Interior arms at
    threshold 0 stride 1, end arms at 0 / 1, top arms
    at 1 / 1, each in the two kinds of the alternating prefix.
    Every arm is a [LadderNest] segment program. *)
From BBB4.Checkers Require Import LadderCheckZeckTr.

(** *** The inner rules: what the nested arms iterate *)
Definition nlad_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list (LRule * list rstep) :=
  [].
Definition nrules_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list LRule := map fst nlad_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Local Notation nrules := nrules_1RB1LC_0LA1RA_0RB0LD_0RA1LD.

Lemma nladder_ok_1RB1LC_0LA1RA_0RB0LD_0RA1LD : check_ladder tm [] nlad_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Lemma nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD : Forall (RuleSound tm false false) nrules.
Proof. apply rule_sound_nil. exact nladder_ok_1RB1LC_0LA1RA_0RB0LD_0RA1LD. Qed.

Definition iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [] [S1;S0] 1 0 [S1;S1]))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [] [S1;S1] 1 0 [S0;S1])) 0 1.
Definition ch_iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SRotR 1);RB (SWin 2);RB (SWinL 3);RB (SCycR 2);RB (SWin 2);RB (SRotL 1);RB (SWin 1);RB (SCycL 2 0);RB (SWin 4)]].
Lemma ok_iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true false nrules iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0] [S1;S0] 1 0 [S1;S1]))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1] [S1;S1] 1 0 [S0;S1])) 0 1.
Definition ch_iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SWin 1);RB (SCycR 2);RB (SWin 4);RB (SCycL 2 0);RB (SWin 1);RB (SWinL 4)]].
Lemma ok_iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true false nrules iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [] [S1;S0] 1 0 [S1;S1;S0;S1]))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [] [S1;S1] 1 0 [S0;S1;S0;S1])) 0 1.
Definition ch_earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SRotR 1);RB (SWin 2);RB (SWinL 3);RB (SCycR 2);RB (SWin 2);RB (SRotL 1);RB (SWin 1);RB (SCycL 2 0);RB (SWin 4)]].
Lemma ok_earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true true nrules earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0] [S1;S0] 1 0 [S1;S1;S0;S1]))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1] [S1;S1] 1 0 [S0;S1;S0;S1])) 0 1.
Definition ch_earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SWin 1);RB (SCycR 2);RB (SWin 4);RB (SCycL 2 0);RB (SWin 1);RB (SWinL 4)]].
Lemma ok_earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true true nrules earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S0] [S1;S0] 1 0 [S1;S0;S1]))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S1] [S1;S1] 1 0 [S1;S1;S0;S1])) 0 1.
Definition ch_tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SWin 2);RB (SWinL 4);RB (SCycR 2);RB (SWin 3);RB (SWinR 7);RB (SCycL 2 0);RB (SWin 6)]].
Lemma ok_tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true true nrules tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0;S1] [] 0 0 []))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S1;S1;S0;S1] [] 0 0 [])) 0 1.
Definition ch_tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SWin 4);RB (SWinR 8);RB (SWinL 4)]].
Lemma ok_tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true true nrules tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD : LRule :=
  mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S0;S1;S0] [S1;S0] 1 0 [S1;S0;S1]))
          (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S1;S1] [S1;S1] 1 0 [S1;S1;S0;S1])) 0 1.
Definition ch_tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD : list nseg :=
  [NCh [RB (SWin 3);RB (SCycR 2);RB (SWin 3);RB (SWinR 7);RB (SCycL 2 0);RB (SWin 3);RB (SWinL 4)]].
Lemma ok_tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  check_narm tm true true nrules tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD ch_tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD (i r : nat) : LRule :=
  match i, r with | 0, 0 => iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD | 1, 0 => iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD | _, _ => iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD end.
Definition earm_1RB1LC_0LA1RA_0RB0LD_0RA1LD (i r : nat) : LRule :=
  match i, r with | 0, 0 => earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD | 1, 0 => earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD | _, _ => earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD end.
Definition tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD (i r : nat) : LRule :=
  match i, r with | 0, 1 => tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD | 1, 0 => tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD | 1, 1 => tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD | _, _ => tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD end.

Definition vis_1RB1LC_0LA1RA_0RB0LD_0RA1LD (i r : nat) (t : Instr) : list lstep :=
  match i, r, t with
  | 0, 1, (StA, S0) => [SWinL 4]
  | 0, 1, (StA, S1) => [SWin 1]
  | 0, 1, (StB, S0) => [SWin 2;SWinL 4;SCycR 2;SWinR 5]
  | 0, 1, (StB, S1) => [SWin 0]
  | 0, 1, (StC, S0) => [SWin 2;SWinL 4;SCycR 2;SWin 3;SWinR 7;SCycL 2 0;SWin 5]
  | 0, 1, (StC, S1) => [SWin 2]
  | 0, 1, (StD, S0) => [SWinL 3]
  | 0, 1, (StD, S1) => [SWin 2;SWinL 4;SCycR 2;SWinR 8]
  | 1, 0, (StA, S0) => [SWin 1]
  | 1, 0, (StA, S1) => [SWinR 7]
  | 1, 0, (StB, S0) => [SWinR 6]
  | 1, 0, (StB, S1) => [SWin 0]
  | 1, 0, (StC, S0) => [SWin 4;SWinR 8;SWinL 3]
  | 1, 0, (StC, S1) => [SWinR 8]
  | 1, 0, (StD, S0) => [SWin 4;SWinR 8;SWinL 1]
  | 1, 0, (StD, S1) => [SWinR 9]
  | 1, 1, (StA, S0) => [SWin 1]
  | 1, 1, (StA, S1) => [SWin 3;SCycR 2;SWinR 6]
  | 1, 1, (StB, S0) => [SWin 3;SCycR 2;SWinR 5]
  | 1, 1, (StB, S1) => [SWin 0]
  | 1, 1, (StC, S0) => [SWin 3;SCycR 2;SWin 3;SWinR 7;SCycL 2 0;SWinL 6]
  | 1, 1, (StC, S1) => [SWin 3;SCycR 2;SWinR 7]
  | 1, 1, (StD, S0) => [SWin 3;SCycR 2;SWin 3;SWinR 7;SCycL 2 0;SWinL 4]
  | 1, 1, (StD, S1) => [SWin 3;SCycR 2;SWinR 8]
  | _, _, _ => []
  end.

Definition vsegs_1RB1LC_0LA1RA_0RB0LD_0RA1LD (i r : nat) (t : Instr) : list nseg :=
  match i, r, t with
  | 0, 1, (StA, S0) => []
  | 0, 1, (StA, S1) => []
  | 0, 1, (StB, S0) => []
  | 0, 1, (StB, S1) => []
  | 0, 1, (StC, S0) => []
  | 0, 1, (StC, S1) => []
  | 0, 1, (StD, S0) => []
  | 0, 1, (StD, S1) => []
  | 1, 0, (StA, S0) => []
  | 1, 0, (StA, S1) => []
  | 1, 0, (StB, S0) => []
  | 1, 0, (StB, S1) => []
  | 1, 0, (StC, S0) => []
  | 1, 0, (StC, S1) => []
  | 1, 0, (StD, S0) => []
  | 1, 0, (StD, S1) => []
  | 1, 1, (StA, S0) => []
  | 1, 1, (StA, S1) => []
  | 1, 1, (StB, S0) => []
  | 1, 1, (StB, S1) => []
  | 1, 1, (StC, S0) => []
  | 1, 1, (StC, S1) => []
  | 1, 1, (StD, S0) => []
  | 1, 1, (StD, S1) => []
  | _, _, _ => []
  end.

Lemma iarm_reach_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 0 + 1 ->
  ReachL tm (negb (fm_left FAM)) (fm_left FAM) (lr_lhs (iarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)) (lr_rhs (iarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)).
Proof. intros i r Hi Hr.
  destruct i as [|i].
  {
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_iarm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_iarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_lhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 0 + 1 ->
  lr_lhs (iarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r) = cls_conf FAM (cls_sideW FAM (zu i) [0;1] r (astride 0 1 r) [0;0]).
Proof. intros i r Hi Hr.
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_rhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 0 + 1 ->
  lr_rhs (iarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r) = cls_conf FAM (cls_sideW FAM (zu0 i) [0;0] r (astride 0 1 r) [1;0]).
Proof. intros i r Hi Hr.
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma earm_reach_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 0 + 1 ->
  ReachL tm true true (lr_lhs (earm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)) (lr_rhs (earm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)).
Proof. intros i r Hi Hr.
  destruct i as [|i].
  {
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_earm0_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_earm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma earm_lhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 0 + 1 ->
  lr_lhs (earm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r) = cls_conf FAM (run_sideW FAM [0;1] r (astride 0 1 r) 0 0 (zu i) [0]).
Proof. intros i r Hi Hr.
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma earm_rhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 0 + 1 ->
  lr_rhs (earm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r) = cls_conf FAM (run_sideW FAM [0;0] r (astride 0 1 r) 0 0 (zu0 i) [1]).
Proof. intros i r Hi Hr.
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma tarm_reach_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 1 + 1 -> (i = 0 -> 0 < r) ->
  ReachL tm true true (lr_lhs (tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)) (lr_rhs (tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)).
Proof. intros i r Hi Hr H0.
  destruct i as [|i].
  {
    destruct r as [|r].
    { exfalso; specialize (H0 eq_refl); lia. }
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_tarm0_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_tarm1_0_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    destruct r as [|r].
    { eapply narm_reach; [exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD | exact ok_tarm1_1_1RB1LC_0LA1RA_0RB0LD_0RA1LD]. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma tarm_lhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 1 + 1 -> (i = 0 -> 0 < r) ->
  lr_lhs (tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r) = cls_conf FAM (run_sideW FAM [0;1] r (astride 1 1 r) 0 0 (zu i) []).
Proof. intros i r Hi Hr H0.
  destruct i as [|i].
  {
    destruct r as [|r].
    { exfalso; specialize (H0 eq_refl); lia. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma tarm_rhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r, i < 2 -> r < 1 + 1 -> (i = 0 -> 0 < r) ->
  lr_rhs (tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r) = cls_conf FAM (run_sideW FAM [0;0] r (astride 1 1 r) 0 0 (zu0 i) [0]).
Proof. intros i r Hi Hr H0.
  destruct i as [|i].
  {
    destruct r as [|r].
    { exfalso; specialize (H0 eq_refl); lia. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma vis_ok_1RB1LC_0LA1RA_0RB0LD_0RA1LD : forall i r t, ~ In t pins_1RB1LC_0LA1RA_0RB0LD_0RA1LD -> i < 2 -> r < 1 + 1 ->
  (i = 0 -> 0 < r) ->
  nfire tm true true nrules (vsegs_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r t) (vis_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r t) (lr_lhs (tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD i r)) = Some t.
Proof. intros i r t Hnp Hi Hr H0.
  destruct i as [|i].
  {
    destruct r as [|r].
    { exfalso; specialize (H0 eq_refl); lia. }
    destruct r as [|r].
    { destruct t as [q s]; destruct q, s; try (exfalso; apply Hnp; simpl; tauto); vm_compute; reflexivity. }
    exfalso; lia.
  }
  destruct i as [|i].
  {
    destruct r as [|r].
    { destruct t as [q s]; destruct q, s; try (exfalso; apply Hnp; simpl; tauto); vm_compute; reflexivity. }
    destruct r as [|r].
    { destruct t as [q s]; destruct q, s; try (exfalso; apply Hnp; simpl; tauto); vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma bootl_1RB1LC_0LA1RA_0RB0LD_0RA1LD :
  stepn tm 50 InitES = Some (lift (fam_cfg FAM ([0], 0, 0))).
Proof.
  assert (H : match csteps tm 50 c0 with
              | Some c => ceqb c (fam_cfg FAM ([0], 0, 0))
              | None => false end = true) by (vm_compute; reflexivity).
  destruct (csteps tm 50 c0) as [c|] eqn:E; [|discriminate].
  rewrite <- lift_c0, (csteps_lift _ _ _ _ E). f_equal. apply ceqb_lift. exact H.
Qed.

Theorem nqhtr_1RB1LC_0LA1RA_0RB0LD_0RA1LD : NeverQuasiHaltsTr tm_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Proof.
  eapply (boardZ_neverqhtr tm_1RB1LC_0LA1RA_0RB0LD_0RA1LD pins_1RB1LC_0LA1RA_0RB0LD_0RA1LD FAM
                 iarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD 0 1 earm_1RB1LC_0LA1RA_0RB0LD_0RA1LD 0 1
                 tarm_1RB1LC_0LA1RA_0RB0LD_0RA1LD 1 1 nrules vsegs_1RB1LC_0LA1RA_0RB0LD_0RA1LD vis_1RB1LC_0LA1RA_0RB0LD_0RA1LD [0]).
  - vm_compute; reflexivity.
  - vm_compute; lia.
  - lia.
  - exact iarm_reach_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact iarm_lhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact iarm_rhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - lia.
  - exact earm_reach_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact earm_lhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact earm_rhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - lia.
  - lia.
  - exact tarm_reach_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact tarm_lhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact tarm_rhs_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact nrules_sound_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact vis_ok_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
  - exact bootl_1RB1LC_0LA1RA_0RB0LD_0RA1LD.
Qed.
