(** * LDR_0RB1LA_1LC1RD_0RD0LC_0LA1RB: machine 0RB1LA_1LC1RD_0RD0LC_0LA1RB, boarded by the STAGE-B LADDER.

    GENERATED by tools/ladder/emit_ladder.py from a `valfam.close`
    certificate -- an UNTRUSTED prover.  Every line below is re-run by the
    Coq kernel: [check_ladder] validates the ladder rules against the rules
    before them, [check_arm] replays every arm, and both are closed by
    [vm_compute].  A wrong chain makes the replay return [None] and this
    file fails to compile.

    The certificate's four PARAMETERS -- the fill law per phase with the
    phase it lands in, the terminator of each phase, the counter's code and
    its step per anchor visit -- arrive as fields of a [LadderFam.Fam]
    value, not as definitions in the kernel (LADDER_PLAN.md 4f).

    Axiom footprint: [functional_extensionality_dep], via [CTape.lift]. *)
From Coq Require Import Arith Lia Bool List.
From BBB4 Require Import BBB4_Statement CTape.
From BBB4.Census Require Import TNF_QH.
From BBB4.Counters Require Import WTape LapGlueQuiet.
From BBB4.Checkers Require Import LapDecider LapAvoid LadderKernel LadderFam.
From BBB4.Checkers Require Import LadderCheck.
Import ListNotations.

Definition mk_0RB1LA_1LC1RD_0RD0LC_0LA1RB (w : Sym) (d : Dir) (n : St) : option Trans :=
  Some (mkTrans w d n).
Local Notation mk := mk_0RB1LA_1LC1RD_0RD0LC_0LA1RB.

(** 0RB1LA_1LC1RD_0RD0LC_0LA1RB *)
Definition tm_0RB1LA_1LC1RD_0RD0LC_0LA1RB : TM := fun q s => match q, s with
  | StA, S0 => mk S0 DR StB
  | StA, S1 => mk S1 DL StA
  | StB, S0 => mk S1 DL StC
  | StB, S1 => mk S1 DR StD
  | StC, S0 => mk S0 DR StD
  | StC, S1 => mk S0 DL StC
  | StD, S0 => mk S0 DL StA
  | StD, S1 => mk S1 DR StB
  end.
Local Notation tm := tm_0RB1LA_1LC1RD_0RD0LC_0LA1RB.

(** ** The family, as DATA

    The successor is a PARAMETER here, not a law: [fam_succ] reads the fill
    of the phase it is in, the code the digits are written in, and the step
    the counter advances by, all off this record. *)
Definition fam_0RB1LA_1LC1RD_0RD0LC_0LA1RB : Fam := mkFam 2 [[S0];[S1]] [] [[]] Binary 1 [mkFill 1 [] 0 [1] 0] StC S0 false [].
Local Notation FAM := fam_0RB1LA_1LC1RD_0RD0LC_0LA1RB.

(** ** The ladder, as DATA

    3 window rule(s).  [check_ladder] validates rule i against rules
    0..i-1 only, and [rule_sound] -- ONE theorem, by induction on ladder
    POSITION -- turns that into soundness for all of them. *)
Definition lad_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list (LRule * list rstep) :=
  [(mkLRule (mkC StC (mkS [S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) (mkC StC (mkS [] [] 0 0 []) S1 (mkS [S0] [] 0 0 [])) 0 1, [RB (SWin 1)]);
   (mkLRule (mkC StA (mkS [S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) (mkC StA (mkS [] [] 0 0 []) S1 (mkS [S1] [] 0 0 [])) 0 1, [RB (SWin 1)]);
   (mkLRule (mkC StB (mkS [] [] 0 0 []) S1 (mkS [S1;S1] [] 0 0 [])) (mkC StB (mkS [S1;S1] [] 0 0 []) S1 (mkS [] [] 0 0 [])) 0 2, [RB (SWin 2)])].
Local Notation lad := lad_0RB1LA_1LC1RD_0RD0LC_0LA1RB.

Definition rules_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list LRule := map fst lad.
Local Notation rules := rules_0RB1LA_1LC1RD_0RD0LC_0LA1RB.

Lemma ladder_ok_0RB1LA_1LC1RD_0RD0LC_0LA1RB : check_ladder tm [] lad = true.
Proof. vm_compute. reflexivity. Qed.

Lemma rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB : Forall (RuleSound tm false false) rules.
Proof. apply rule_sound_nil. exact ladder_ok_0RB1LA_1LC1RD_0RD0LC_0LA1RB. Qed.

(** ** The arms, as DATA

    Each is a rule the kernel re-derives from the machine.  [el]/[er] record
    whether that side's tail is known empty: the fill arm must see the end
    of the counter, the interior arms hold against an arbitrary tail. *)
(* C[0] L<> R<>  ==>  C[0] L<> R<1^1>   [4 steps] *)
Definition arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWinR 4)].
Lemma ok_arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm15_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^8>  ==>  C[0] L<> R<0^8 1^1>   [36 steps] *)
Definition arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 36.
Definition ch_arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 8);RB (SWinR 28)].
Lemma ok_arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm117_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^9>  ==>  C[0] L<> R<0^9 1^1>   [20 steps] *)
Definition arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1;S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 9);RB (SWinR 11)].
Lemma ok_arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm141_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^1>  ==>  C[0] L<> R<0^1 1^1>   [4 steps] *)
Definition arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S1] [] 0 0 [])) 0 4.
Definition ch_arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 1);RB (SWinR 3)].
Lemma ok_arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm20_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^2>  ==>  C[0] L<> R<0^2 1^1>   [12 steps] *)
Definition arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S1] [] 0 0 [])) 0 12.
Definition ch_arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 2);RB (SWinR 10)].
Lemma ok_arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm26_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^3>  ==>  C[0] L<> R<0^3 1^1>   [8 steps] *)
Definition arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S1] [] 0 0 [])) 0 8.
Definition ch_arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 3);RB (SWinR 5)].
Lemma ok_arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm34_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^4>  ==>  C[0] L<> R<0^4 1^1>   [20 steps] *)
Definition arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 4);RB (SWinR 16)].
Lemma ok_arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm45_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^5>  ==>  C[0] L<> R<0^5 1^1>   [12 steps] *)
Definition arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 12.
Definition ch_arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 5);RB (SWinR 7)].
Lemma ok_arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm58_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^6>  ==>  C[0] L<> R<0^6 1^1>   [28 steps] *)
Definition arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 28.
Definition ch_arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 6);RB (SWinR 22)].
Lemma ok_arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm75_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^7>  ==>  C[0] L<> R<0^7 1^1>   [16 steps] *)
Definition arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1;S1] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 7);RB (SWinR 9)].
Lemma ok_arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true true arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm94_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<0^1+y0 1^1+y1>  ==>  C[0] L<> R<1^1 0^y0 1^1+y1>   [4 steps] *)
Definition arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 4)].
Lemma ok_arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm4_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^1 0^1+y0 #^1>  ==>  C[0] L<> R<0^1 1^1 0^y0 #^1>   [4 steps] *)
Definition arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S1] [] 0 0 [])) 0 4.
Definition ch_arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 4)].
Lemma ok_arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm35_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^2 0^1+y0 #^1>  ==>  C[0] L<> R<0^2 1^1 0^y0 #^1>   [12 steps] *)
Definition arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S1] [] 0 0 [])) 0 12.
Definition ch_arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 12)].
Lemma ok_arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm60_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^3 0^1+y0 #^1>  ==>  C[0] L<> R<0^3 1^1 0^y0 #^1>   [8 steps] *)
Definition arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S1] [] 0 0 [])) 0 8.
Definition ch_arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 8)].
Lemma ok_arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm97_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^4 0^3 #^1>  ==>  C[0] L<> R<0^4 1^1 0^2 #^1>   [20 steps] *)
Definition arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S0;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1;S0;S0] [] 0 0 [])) 0 20.
Definition ch_arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 20)].
Lemma ok_arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm101_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^5 0^2 #^1>  ==>  C[0] L<> R<0^5 1^1 0^1 #^1>   [12 steps] *)
Definition arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S1;S0] [] 0 0 [])) 0 12.
Definition ch_arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 12)].
Lemma ok_arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm105_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^6 0^1 #^1>  ==>  C[0] L<> R<0^6 1^1 #^1>   [28 steps] *)
Definition arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 28.
Definition ch_arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 28)].
Lemma ok_arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm109_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^4 0^4 #^1>  ==>  C[0] L<> R<0^4 1^1 0^3 #^1>   [20 steps] *)
Definition arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S0;S0;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1;S0;S0;S0] [] 0 0 [])) 0 20.
Definition ch_arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 20)].
Lemma ok_arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm121_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^5 0^3 #^1>  ==>  C[0] L<> R<0^5 1^1 0^2 #^1>   [12 steps] *)
Definition arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S0;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S1;S0;S0] [] 0 0 [])) 0 12.
Definition ch_arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 12)].
Lemma ok_arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm125_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^6 0^2 #^1>  ==>  C[0] L<> R<0^6 1^1 0^1 #^1>   [28 steps] *)
Definition arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S1;S0] [] 0 0 [])) 0 28.
Definition ch_arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 28)].
Lemma ok_arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm129_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^7 0^1 #^1>  ==>  C[0] L<> R<0^7 1^1 #^1>   [16 steps] *)
Definition arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S1;S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 16.
Definition ch_arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 16)].
Lemma ok_arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm133_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^4 0^1 #^1>  ==>  C[0] L<> R<0^4 1^1 #^1>   [20 steps] *)
Definition arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1] [] 0 0 [])) 0 20.
Definition ch_arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 20)].
Lemma ok_arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm67_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^4 0^2 #^1>  ==>  C[0] L<> R<0^4 1^1 0^1 #^1>   [20 steps] *)
Definition arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S0;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S1;S0] [] 0 0 [])) 0 20.
Definition ch_arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 20)].
Lemma ok_arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm82_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<1^5 0^1 #^1>  ==>  C[0] L<> R<0^5 1^1 #^1>   [12 steps] *)
Definition arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1;S1;S1;S1;S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0;S0;S0;S0;S1] [] 0 0 [])) 0 12.
Definition ch_arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 12)].
Lemma ok_arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm86_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(* C[0] L<> R<0^1+y0 1^1+y1 0^1+y2 1^1+y3 #^1>  ==>  C[0] L<> R<1^1 0^y0 1^1+y1 0^1+y2 1^1+y3 #^1>   [4 steps] *)
Definition arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 4)].
Lemma ok_arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.
Lemma sound_arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB : RuleSound tm true false arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Proof. eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_arm8_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. Qed.

(** ** What this board establishes

    25 of 25 arms of the certificate are re-derived by the kernel and
    sound: each [sound_*] is a theorem that the machine, from that arm's
    left-hand side and against any tail the flags permit, reaches the arm's
    right-hand side in exactly the certificate's step count. *)

(** ** The closure: from the RULES to [NeverQuasiHaltsSt]

    The arms below are the case split of [LadderCheck.digs_decomp], built
    from the FAMILY rather than mined: interior arms for the digits below the
    top, and fill arms.  Every certificate arm above is one of these with its
    run lengths pinned to their lower bounds, which is why 25 of them
    collapse to 5 here.

    Both classes are indexed by [LadderCheck]'s ONE arm scheme -- flat below
    a threshold, residue-and-stride at or above it.  The interior class runs
    at threshold 1 stride 2, the fill class at threshold 1
    stride 2.

    [board_neverqh] consumes them, the boot, and one chain per state per fill
    arm, and returns the machine-level theorem. *)
Definition iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [] 0 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [] 0 0 [])) 0 4.
Definition ch_iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 4)].
Lemma ok_iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB
            ch_iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [S1;S1] 1 0 [S0]))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [S0;S0] 1 0 [S1])) 4 4.
Definition ch_iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 1);RB (SCycR 2);RB (SWin 2);RB (SCycL 2 0);RB (SWin 1)].
Lemma ok_iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB
            ch_iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1] [S1;S1] 1 0 [S0]))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0;S0] [S0;S0] 1 0 [S1])) 8 12.
Definition ch_iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 2);RB (SCycR 2);RB (SWin 2);RB (SCycL 2 0);RB (SWin 4);RB (SCycR 2);RB (SWin 2);RB (SCycL 2 0);RB (SWin 2)].
Lemma ok_iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true false rules iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB
            ch_iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.

Definition iarm_0RB1LA_1LC1RD_0RD0LC_0LA1RB (d r : nat) : LRule :=
  match d, r with
  | 0, 0 => iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB
  | 0, 1 => iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB
  | 0, 2 => iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB
  | _, _ => iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB   (* unreachable: only d < b-1 and r < N0 + st *)
  end.

Definition farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1] [S1;S1] 1 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [S0;S0] 1 0 [S1])) 4 4.
Definition ch_farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 1);RB (SCycR 2);RB (SWinR 2);RB (SCycL 2 0);RB (SWin 1)].
Lemma ok_farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.

Definition farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB : LRule :=
  mkLRule (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S1;S1] [S1;S1] 1 0 []))
          (mkC StC (mkS [] [] 0 0 []) S0 (mkS [S0] [S0;S0] 1 0 [S0;S1])) 8 12.
Definition ch_farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB : list rstep := [RB (SWin 2);RB (SCycR 2);RB (SWinR 2);RB (SCycL 2 0);RB (SWin 4);RB (SCycR 2);RB (SWin 2);RB (SCycL 2 0);RB (SWin 2);RB (SUnrotR 1)].
Lemma ok_farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB :
  check_arm tm true true rules farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB ch_farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB = true.
Proof. vm_compute. reflexivity. Qed.

(** The fill arms.  Both tails are known empty -- they are the only arms
    that see the end of the counter -- and the arm at index [r] has [r]
    guaranteed block copies materialised into [s_pre], without which it has
    no chain at all.  [fm1]/[fm2] say how the fill target's own guaranteed
    copies divide about the block. *)
Definition farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB (r : nat) : LRule :=
  match r with
  | 1 => farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB
  | 2 => farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB
  | _ => farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB   (* unreachable: only 0 < r < N0 + st *)
  end.

Definition fm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB (r : nat) : nat := match r with | 1 => 1 | 2 => 1 | _ => 0 end.
Definition fm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB (r : nat) : nat := match r with | 1 => 0 | 2 => 1 | _ => 0 end.

(** One chain per RECURRING state per fill arm.  [vis_of_run] turns each
    into a visit, and [tops_cofinal] says those anchors keep coming. *)
Definition vis_0RB1LA_1LC1RD_0RD0LC_0LA1RB (r : nat) (q : St) : list lstep :=
  match r, q with
  | 1, StA => [SWin 1;SCycR 2;SWinR 2;SCycL 2 0;SWin 3]
  | 1, StB => [SWin 1;SCycR 2;SWinR 1]
  | 1, StC => []
  | 1, StD => [SWin 1]
  | 2, StA => [SWin 2;SCycR 2;SWinR 2]
  | 2, StB => [SWin 2]
  | 2, StC => []
  | 2, StD => [SWin 1]
  | _, _ => []
  end.

Lemma iarm_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall d r,
  d < fm_b FAM - 1 -> r < 1 + 2 ->
  RuleSound tm (negb (fm_left FAM)) (fm_left FAM) (iarm_0RB1LA_1LC1RD_0RD0LC_0LA1RB d r).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_iarm0_0_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. }
    destruct r as [|r].
    { eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_iarm0_1_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. }
    destruct r as [|r].
    { eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_iarm0_2_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_lhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall d r,
  d < fm_b FAM - 1 -> r < 1 + 2 ->
  lr_lhs (iarm_0RB1LA_1LC1RD_0RD0LC_0LA1RB d r)
    = cls_conf FAM (cls_side FAM (fm_b FAM - 1) r (astride 1 2 r)
                      [d]).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_rhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall d r,
  d < fm_b FAM - 1 -> r < 1 + 2 ->
  lr_rhs (iarm_0RB1LA_1LC1RD_0RD0LC_0LA1RB d r)
    = cls_conf FAM (cls_side FAM 0 r (astride 1 2 r) [S d]).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    destruct r as [|r].
    { vm_compute; reflexivity. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma iarm_cb_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall d r,
  d < fm_b FAM - 1 -> r < 1 + 2 -> 0 < lr_cb (iarm_0RB1LA_1LC1RD_0RD0LC_0LA1RB d r).
Proof.
  intros d r Hd Hr. vm_compute in Hd.
  destruct d as [|d].
  {
    destruct r as [|r].
    { vm_compute; lia. }
    destruct r as [|r].
    { vm_compute; lia. }
    destruct r as [|r].
    { vm_compute; lia. }
    exfalso; lia.
  }
  exfalso; lia.
Qed.

Lemma farm_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall r, 0 < r -> r < 1 + 2 ->
  RuleSound tm true true (farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB r).
Proof.
  intros r H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_farm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. }
  destruct r as [|r].
  { eapply arm_sound; [exact rules_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB | exact ok_farm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB]. }
  exfalso; lia.
Qed.

Lemma farm_lhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall r, 0 < r -> r < 1 + 2 ->
  lr_lhs (farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB r)
    = cls_conf FAM (run_side FAM (fm_b FAM - 1) r (astride 1 2 r)
                      0 0 [] []).
Proof.
  intros r H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { vm_compute; reflexivity. }
  destruct r as [|r].
  { vm_compute; reflexivity. }
  exfalso; lia.
Qed.

Lemma farm_rhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall r, 0 < r -> r < 1 + 2 ->
  lr_rhs (farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB r)
    = cls_conf FAM (run_side FAM (f_mid (fam_fill FAM 0)) (fm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB r)
                      (astride 1 2 r) (fm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB r) 0
                      (f_pre (fam_fill FAM 0)) (f_suf (fam_fill FAM 0))).
Proof.
  intros r H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { vm_compute; reflexivity. }
  destruct r as [|r].
  { vm_compute; reflexivity. }
  exfalso; lia.
Qed.

Lemma farm_cb_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall r, 0 < r -> r < 1 + 2 ->
  0 < lr_cb (farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB r).
Proof.
  intros r H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { vm_compute; lia. }
  destruct r as [|r].
  { vm_compute; lia. }
  exfalso; lia.
Qed.

Lemma fm12_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall r, 0 < r -> r < 1 + 2 ->
  fm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB r + fm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB r
  + (length (f_pre (fam_fill FAM 0)) + length (f_suf (fam_fill FAM 0)))
  = r + f_s (fam_fill FAM 0).
Proof.
  intros r H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { vm_compute; lia. }
  destruct r as [|r].
  { vm_compute; lia. }
  exfalso; lia.
Qed.

Lemma boot_0RB1LA_1LC1RD_0RD0LC_0LA1RB : csteps tm 2 c0 = Some (fam_cfg FAM ([1], 0, 0)).
Proof. vm_compute. reflexivity. Qed.

Lemma vis_ok_0RB1LA_1LC1RD_0RD0LC_0LA1RB : forall r q, 0 < r -> r < 1 + 2 ->
  srun_st tm true true (vis_0RB1LA_1LC1RD_0RD0LC_0LA1RB r q) (lr_lhs (farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB r)) = Some q.
Proof.
  intros r q H0 Hr.
  destruct r as [|r].
  { exfalso; lia. }
  destruct r as [|r].
  { destruct q; vm_compute; reflexivity. }
  destruct r as [|r].
  { destruct q; vm_compute; reflexivity. }
  exfalso; lia.
Qed.

(** The machine-level theorem.  Every argument is either a [RuleSound] the
    Stage-B kernel discharged, or an equation two [vm_compute]s decide. *)
Theorem nqh_0RB1LA_1LC1RD_0RD0LC_0LA1RB : NeverQuasiHaltsSt tm.
Proof.
  apply (board_neverqh tm FAM iarm_0RB1LA_1LC1RD_0RD0LC_0LA1RB 1 2
                       farm_0RB1LA_1LC1RD_0RD0LC_0LA1RB 1 2
                       fm1_0RB1LA_1LC1RD_0RD0LC_0LA1RB fm2_0RB1LA_1LC1RD_0RD0LC_0LA1RB vis_0RB1LA_1LC1RD_0RD0LC_0LA1RB
                       [1] 2).
  - vm_compute; lia.
  - vm_compute; reflexivity.
  - vm_compute; reflexivity.
  - vm_compute; repeat constructor.
  - vm_compute; repeat constructor.
  - vm_compute; lia.
  - vm_compute; lia.
  - vm_compute; reflexivity.
  - exact fm12_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - repeat constructor.
  - vm_compute; lia.
  - exact boot_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - lia.
  - exact iarm_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact iarm_lhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact iarm_rhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact iarm_cb_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - lia.
  - lia.
  - exact farm_sound_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact farm_lhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact farm_rhs_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact farm_cb_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
  - exact vis_ok_0RB1LA_1LC1RD_0RD0LC_0LA1RB.
Qed.
