(** GENERATED by tools/gen_reroot.py, EXTENDED by tools/wire_wave3.py -- DO NOT EDIT.

    The census R_QH lookup tier data: the wave-1 re-root boards
    (rerootqh_00..04), the wave-2 staged re-root boards
    (the Machines/RerootStage batches), and the wave-3 irules-QH
    boards (Machines/IRulesQHStage/IQHStage_*, via
    Checkers/IRules/MetaBlkPfxQH.v).  Composed with the
    proven-QH tier (Run.v) as extra R_QH lookup members. *)
From Coq Require Import List.
From BBB4 Require Import BBB4_Statement.
From BBB4.Census Require Import TNF_QH RerootQH_00 RerootQH_01 RerootQH_02 RerootQH_03 RerootQH_04.
From BBB4.Machines.RerootStage Require Import RRStage_00 RRStage_01 RRStage_02 RRStage_03 RRStage_04 RRStage_05 RRStage_06 RRStage_07 RRStage_08 RRStage_09 RRStage_10 RRStage_11 RRStage_12 RRStage_13 RRStage_14 RRStage_15.
From BBB4.Machines.IRulesQHStage Require Import IQHStage_00 IQHStage_01 IQHStage_02 IQHStage_03 IQHStage_04 IQHStage_05 IQHStage_06 IQHStage_07 IQHStage_08 IQHStage_09 IQHStage_10.
Import ListNotations.

Definition reroot_qh_list : list TM :=
  rerootqh_00 ++ rerootqh_01 ++ rerootqh_02 ++ rerootqh_03 ++ rerootqh_04 ++ rrstage_00 ++ rrstage_01 ++ rrstage_02 ++ rrstage_03 ++ rrstage_04 ++ rrstage_05 ++ rrstage_06 ++ rrstage_07 ++ rrstage_08 ++ rrstage_09 ++ rrstage_10 ++ rrstage_11 ++ rrstage_12 ++ rrstage_13 ++ rrstage_14 ++ rrstage_15 ++ iqhstage_00 ++ iqhstage_01 ++ iqhstage_02 ++ iqhstage_03 ++ iqhstage_04 ++ iqhstage_05 ++ iqhstage_06 ++ iqhstage_07 ++ iqhstage_08 ++ iqhstage_09 ++ iqhstage_10.

Lemma reroot_qh_all :
  Forall (fun tm => NonHalt tm /\ QHBound 2000 tm /\ QuasiHaltsSt tm)
         reroot_qh_list.
Proof.
  unfold reroot_qh_list.
  apply Forall_app; split; [exact rerootqh_00_all|].
  apply Forall_app; split; [exact rerootqh_01_all|].
  apply Forall_app; split; [exact rerootqh_02_all|].
  apply Forall_app; split; [exact rerootqh_03_all|].
  apply Forall_app; split; [exact rerootqh_04_all|].
  apply Forall_app; split; [exact rrstage_00_all|].
  apply Forall_app; split; [exact rrstage_01_all|].
  apply Forall_app; split; [exact rrstage_02_all|].
  apply Forall_app; split; [exact rrstage_03_all|].
  apply Forall_app; split; [exact rrstage_04_all|].
  apply Forall_app; split; [exact rrstage_05_all|].
  apply Forall_app; split; [exact rrstage_06_all|].
  apply Forall_app; split; [exact rrstage_07_all|].
  apply Forall_app; split; [exact rrstage_08_all|].
  apply Forall_app; split; [exact rrstage_09_all|].
  apply Forall_app; split; [exact rrstage_10_all|].
  apply Forall_app; split; [exact rrstage_11_all|].
  apply Forall_app; split; [exact rrstage_12_all|].
  apply Forall_app; split; [exact rrstage_13_all|].
  apply Forall_app; split; [exact rrstage_14_all|].
  apply Forall_app; split; [exact rrstage_15_all|].
  apply Forall_app; split; [exact iqhstage_00_all|].
  apply Forall_app; split; [exact iqhstage_01_all|].
  apply Forall_app; split; [exact iqhstage_02_all|].
  apply Forall_app; split; [exact iqhstage_03_all|].
  apply Forall_app; split; [exact iqhstage_04_all|].
  apply Forall_app; split; [exact iqhstage_05_all|].
  apply Forall_app; split; [exact iqhstage_06_all|].
  apply Forall_app; split; [exact iqhstage_07_all|].
  apply Forall_app; split; [exact iqhstage_08_all|].
  apply Forall_app; split; [exact iqhstage_09_all|].
  exact iqhstage_10_all.
Qed.
