(** GENERATED by tools/gen_gsplit_deeper.py -- do not edit.
    Deeper split of heavy unit GGGH_GGGH_GG_1LC_0LB_0RA_1RD: its machine reaches hole StD
    reading S0 at step 6; parent pointer None, 16 fills. *)
From Coq Require Import Arith Lia Bool List.
From BBB4 Require Import BBB4_Statement.
From BBB4.Census Require Import TNF_QH Decide Deferred_Data Run Run_Split.
From BBB4.Census Require Import Run_Split_GGGH_GG_1LC_0LB_0RA.
Import ListNotations.

Set Default Goal Selector "!".

Definition ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD : TM := node_tm (gggchild_GGGH_GG_1LC_0LB_0RA S1 DR StD).

Definition gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD (w4 : Sym) (d4 : Dir) (nx4 : St) : TNF_Node :=
  mkNode (TM_upd' ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD StD S0 (Some (mkTrans w4 d4 nx4)))
         (ptr_after None nx4).

Definition q_gggsub_GGGH_GGGH_GG_1LC_0LB_0RA_1RD (w4 : Sym) (d4 : Dir) (nx4 : St) : SearchQueue :=
  ([gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4], []).

Lemma ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD_used : ~ UnusedState ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD StD.
Proof.
  intros (Hin & _ & _).
  refine (Hin StA S1 (mkTrans S1 DR StD) _ eq_refl).
  reflexivity.
Qed.

Lemma gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD_WF : forall w4 d4 nx4,
  trans_ok None (mkTrans w4 d4 nx4) = true ->
  Node_WF (gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4).
Proof.
  intros w4 d4 nx4 Hok.
  unfold Node_WF, gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD; simpl.
  rewrite TM_upd'_spec.
  apply (UnusedState_ptr_upd ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD StD S0 (mkTrans w4 d4 nx4) None).
  - reflexivity.
  - exact ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD_used.
  - exact (gggchild_GGGH_GG_1LC_0LB_0RA_WF S1 DR StD eq_refl).
  - exact Hok.
Qed.

Lemma gggsub_decided_GGGH_GGGH_GG_1LC_0LB_0RA_1RD : forall w4 d4 nx4 n,
  trans_ok None (mkTrans w4 d4 nx4) = true ->
  Nat.iter n q_suc (q_gggsub_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4) = ([], []) ->
  NodeDecided B_census D_census (node_tm (gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4)).
Proof.
  intros w4 d4 nx4 n Hok Hempty.
  assert (HWF : SearchQueue_WF B_census D_census
                  (Nat.iter n q_suc (q_gggsub_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4))
                  (gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4)).
  { clear Hempty. induction n.
    - apply SearchQueue_init_spec. apply gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD_WF. exact Hok.
    - simpl. apply SearchQueue_upds_spec; [exact IHn | exact decider_WF]. }
  rewrite Hempty in HWF.
  exact (SearchQueue_empty_decided B_census D_census _ HWF).
Qed.

Lemma cover_GGGH_GGGH_GG_1LC_0LB_0RA_1RD :
  (forall w4 d4 nx4,
     trans_ok None (mkTrans w4 d4 nx4) = true ->
     NodeDecided B_census D_census (node_tm (gggchild_GGGH_GGGH_GG_1LC_0LB_0RA_1RD w4 d4 nx4))) ->
  NodeDecided B_census D_census (node_tm (gggchild_GGGH_GG_1LC_0LB_0RA S1 DR StD)).
Proof.
  intros Hg.
  assert (Hstep : stepn ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD 6 InitES = Some (StD, (tape_move DR S1 (tape_move DR S0 (tape_move DL S1 (tape_move DL S0 (tape_move DL S1 (tape_move DR S1 (mkTape blank_side S0 blank_side))))))))).
  { reflexivity. }
  assert (Hhole : ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD StD (t_head (tape_move DR S1 (tape_move DR S0 (tape_move DL S1 (tape_move DL S0 (tape_move DL S1 (tape_move DR S1 (mkTape blank_side S0 blank_side)))))))) = None) by reflexivity.
  assert (HB : 7 <= B_census) by (unfold B_census; lia).
  pose proof (node_expand_spec B_census D_census ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD None 6
                StD (tape_move DR S1 (tape_move DR S0 (tape_move DL S1 (tape_move DL S0 (tape_move DL S1 (tape_move DR S1 (mkTape blank_side S0 blank_side)))))))
                Hstep Hhole HB (gggchild_GGGH_GG_1LC_0LB_0RA_WF S1 DR StD eq_refl)) as [_ Hexp].
  change (NodeDecided B_census D_census ggm_GGGH_GGGH_GG_1LC_0LB_0RA_1RD).
  apply Hexp.
  intros x' Hin.
  cbn [node_expand node_tm node_ptr filter trans_ok all_trans map
       t_next t_head tape_move St_to_nat Nat.leb In] in Hin.
  destruct Hin as [<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[<-|[]]]]]]]]]]]]]]]]];
    cbn [node_tm];
    first
      [ exact (Hg S0 DL StA eq_refl)
      | exact (Hg S0 DL StB eq_refl)
      | exact (Hg S0 DL StC eq_refl)
      | exact (Hg S0 DL StD eq_refl)
      | exact (Hg S0 DR StA eq_refl)
      | exact (Hg S0 DR StB eq_refl)
      | exact (Hg S0 DR StC eq_refl)
      | exact (Hg S0 DR StD eq_refl)
      | exact (Hg S1 DL StA eq_refl)
      | exact (Hg S1 DL StB eq_refl)
      | exact (Hg S1 DL StC eq_refl)
      | exact (Hg S1 DL StD eq_refl)
      | exact (Hg S1 DR StA eq_refl)
      | exact (Hg S1 DR StB eq_refl)
      | exact (Hg S1 DR StC eq_refl)
      | exact (Hg S1 DR StD eq_refl) ].
Qed.
