(** GENERATED by tools/closeouttr -- DO NOT EDIT.

    Transition-level closeout batch SPB_12: 40 deferred rows, never-QH by lap certificates at the instruction level (LapGlueTr, LAPT boards).
    Collected by tools/closeouttr/gen_closeout_tr.py. *)
From Coq Require Import Arith List ZArith.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.Census Require Import Deferred_Defs.
From BBB4.CloseoutTr Require Import CloseoutKitTr.
(* LAP BUNDLE IMPORT: From BBB4.Machines.CountersTr Require LAPT_1RB1LA_0LA1RC_0RB1RD_1RB0RB LAPT_1RB1LA_0LA1RC_0RD1RD_0LA0RB LAPT_1RB1LA_0LA1RC_0RD1RD_0LD0RB LAPT_1RB1LA_0LA1RC_1LA0RB_______ LAPT_1RB1LA_0LA1RC_1LA1RD_0LA0RB LAPT_1RB1LA_0LA1RC_1LA1RD_0LB0RB LAPT_1RB1LA_0LA1RC_1LA1RD_0LD0RB LAPT_1RB1LA_0LA1RC_1LA1RD_0RB0LC LAPT_1RB1LA_0LA1RC_1LA1RD_0RB0RB LAPT_1RB1LA_0LA1RC_1LA1RD_1LA0RB LAPT_1RB1LA_0LA1RC_1LA1RD_1LC0RB LAPT_1RB1LA_0LA1RC_1LA1RD_1RB0RB LAPT_1RB1LA_0LA1RC_1LB0RB_______ LAPT_1RB1LA_0LA1RC_1LB1RD_0LA0RB LAPT_1RB1LA_0LA1RC_1LB1RD_0LD0RB LAPT_1RB1LA_0LA1RC_1LB1RD_0RB0LC LAPT_1RB1LA_0LA1RC_1LB1RD_0RB0RB LAPT_1RB1LA_0LA1RC_1LB1RD_1LA0RB LAPT_1RB1LA_0LA1RC_1LB1RD_1LC0RB LAPT_1RB1LA_0LA1RC_1LB1RD_1RB0RB LAPT_1RB1LA_0LA1RC_1LC1RD_0LA0RB LAPT_1RB1LA_0LA1RC_1LC1RD_0LB0RB LAPT_1RB1LA_0LA1RC_1LC1RD_0LD0RB LAPT_1RB1LA_0LA1RC_1LC1RD_0RB0LC LAPT_1RB1LA_0LA1RC_1LC1RD_0RB0RB LAPT_1RB1LA_0LA1RC_1LC1RD_1LA0RB LAPT_1RB1LA_0LA1RC_1LC1RD_1LC0RB LAPT_1RB1LA_0LA1RC_1LC1RD_1RB0RB LAPT_1RB1LA_0LA1RC_1RA1RD____0RB LAPT_1RB1LA_0LA1RC_1RA1RD_0RB0LC LAPT_1RB1LA_0LA1RC_1RB0RB_______ LAPT_1RB1LA_0LA1RC_1RB1RD_0LA0RB LAPT_1RB1LA_0LA1RC_1RB1RD_0LB0RB LAPT_1RB1LA_0LA1RC_1RB1RD_0LD0RB LAPT_1RB1LA_0LA1RC_1RB1RD_0RB0LC LAPT_1RB1LA_0LA1RC_1RB1RD_0RB0RB LAPT_1RB1LA_0LA1RC_1RB1RD_1LA0RB LAPT_1RB1LA_0LA1RC_1RB1RD_1LC0RB LAPT_1RB1LA_0LA1RC_1RB1RD_1RB0RB LAPT_1RB1LA_0LA1RC_1RD0LB_0LA0RB. *)
From BBB4.Machines.CountersTr.Bundles Require Import BundleLAPT_028.
From BBB4.Machines.CountersTr.Bundles Require Import BundleLAPT_029.
(* END LAP BUNDLE IMPORT *)
Import ListNotations.

(* spec 1RB1LA_0LA1RC_0RB1RD_1RB0RB *)
Definition r_SPB_12_0000 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t0RB;t1RD;t1RB;t0RB].
Lemma cv_SPB_12_0000 : coversTr (row_to_tm r_SPB_12_0000).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_0RB1RD_1RB0RB.tm_1RB1LA_0LA1RC_0RB1RD_1RB0RB); [exact LAPT_1RB1LA_0LA1RC_0RB1RD_1RB0RB.nqhtr_1RB1LA_0LA1RC_0RB1RD_1RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_0RD1RD_0LA0RB *)
Definition r_SPB_12_0001 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t0RD;t1RD;t0LA;t0RB].
Lemma cv_SPB_12_0001 : coversTr (row_to_tm r_SPB_12_0001).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_0RD1RD_0LA0RB.tm_1RB1LA_0LA1RC_0RD1RD_0LA0RB); [exact LAPT_1RB1LA_0LA1RC_0RD1RD_0LA0RB.nqhtr_1RB1LA_0LA1RC_0RD1RD_0LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_0RD1RD_0LD0RB *)
Definition r_SPB_12_0002 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t0RD;t1RD;t0LD;t0RB].
Lemma cv_SPB_12_0002 : coversTr (row_to_tm r_SPB_12_0002).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_0RD1RD_0LD0RB.tm_1RB1LA_0LA1RC_0RD1RD_0LD0RB); [exact LAPT_1RB1LA_0LA1RC_0RD1RD_0LD0RB.nqhtr_1RB1LA_0LA1RC_0RD1RD_0LD0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA0RB_------ *)
Definition r_SPB_12_0003 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t0RB;tN;tN].
Lemma cv_SPB_12_0003 : coversTr (row_to_tm r_SPB_12_0003).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA0RB_______.tm_1RB1LA_0LA1RC_1LA0RB_______); [exact LAPT_1RB1LA_0LA1RC_1LA0RB_______.nqhtr_1RB1LA_0LA1RC_1LA0RB_______ | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_0LA0RB *)
Definition r_SPB_12_0004 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t0LA;t0RB].
Lemma cv_SPB_12_0004 : coversTr (row_to_tm r_SPB_12_0004).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_0LA0RB.tm_1RB1LA_0LA1RC_1LA1RD_0LA0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_0LA0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_0LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_0LB0RB *)
Definition r_SPB_12_0005 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t0LB;t0RB].
Lemma cv_SPB_12_0005 : coversTr (row_to_tm r_SPB_12_0005).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_0LB0RB.tm_1RB1LA_0LA1RC_1LA1RD_0LB0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_0LB0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_0LB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_0LD0RB *)
Definition r_SPB_12_0006 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t0LD;t0RB].
Lemma cv_SPB_12_0006 : coversTr (row_to_tm r_SPB_12_0006).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_0LD0RB.tm_1RB1LA_0LA1RC_1LA1RD_0LD0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_0LD0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_0LD0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_0RB0LC *)
Definition r_SPB_12_0007 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t0RB;t0LC].
Lemma cv_SPB_12_0007 : coversTr (row_to_tm r_SPB_12_0007).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_0RB0LC.tm_1RB1LA_0LA1RC_1LA1RD_0RB0LC); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_0RB0LC.nqhtr_1RB1LA_0LA1RC_1LA1RD_0RB0LC | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_0RB0RB *)
Definition r_SPB_12_0008 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t0RB;t0RB].
Lemma cv_SPB_12_0008 : coversTr (row_to_tm r_SPB_12_0008).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_0RB0RB.tm_1RB1LA_0LA1RC_1LA1RD_0RB0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_0RB0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_0RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_1LA0RB *)
Definition r_SPB_12_0009 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t1LA;t0RB].
Lemma cv_SPB_12_0009 : coversTr (row_to_tm r_SPB_12_0009).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_1LA0RB.tm_1RB1LA_0LA1RC_1LA1RD_1LA0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_1LA0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_1LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_1LC0RB *)
Definition r_SPB_12_0010 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t1LC;t0RB].
Lemma cv_SPB_12_0010 : coversTr (row_to_tm r_SPB_12_0010).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_1LC0RB.tm_1RB1LA_0LA1RC_1LA1RD_1LC0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_1LC0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_1LC0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LA1RD_1RB0RB *)
Definition r_SPB_12_0011 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LA;t1RD;t1RB;t0RB].
Lemma cv_SPB_12_0011 : coversTr (row_to_tm r_SPB_12_0011).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LA1RD_1RB0RB.tm_1RB1LA_0LA1RC_1LA1RD_1RB0RB); [exact LAPT_1RB1LA_0LA1RC_1LA1RD_1RB0RB.nqhtr_1RB1LA_0LA1RC_1LA1RD_1RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB0RB_------ *)
Definition r_SPB_12_0012 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t0RB;tN;tN].
Lemma cv_SPB_12_0012 : coversTr (row_to_tm r_SPB_12_0012).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB0RB_______.tm_1RB1LA_0LA1RC_1LB0RB_______); [exact LAPT_1RB1LA_0LA1RC_1LB0RB_______.nqhtr_1RB1LA_0LA1RC_1LB0RB_______ | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_0LA0RB *)
Definition r_SPB_12_0013 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t0LA;t0RB].
Lemma cv_SPB_12_0013 : coversTr (row_to_tm r_SPB_12_0013).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_0LA0RB.tm_1RB1LA_0LA1RC_1LB1RD_0LA0RB); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_0LA0RB.nqhtr_1RB1LA_0LA1RC_1LB1RD_0LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_0LD0RB *)
Definition r_SPB_12_0014 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t0LD;t0RB].
Lemma cv_SPB_12_0014 : coversTr (row_to_tm r_SPB_12_0014).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_0LD0RB.tm_1RB1LA_0LA1RC_1LB1RD_0LD0RB); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_0LD0RB.nqhtr_1RB1LA_0LA1RC_1LB1RD_0LD0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_0RB0LC *)
Definition r_SPB_12_0015 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t0RB;t0LC].
Lemma cv_SPB_12_0015 : coversTr (row_to_tm r_SPB_12_0015).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_0RB0LC.tm_1RB1LA_0LA1RC_1LB1RD_0RB0LC); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_0RB0LC.nqhtr_1RB1LA_0LA1RC_1LB1RD_0RB0LC | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_0RB0RB *)
Definition r_SPB_12_0016 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t0RB;t0RB].
Lemma cv_SPB_12_0016 : coversTr (row_to_tm r_SPB_12_0016).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_0RB0RB.tm_1RB1LA_0LA1RC_1LB1RD_0RB0RB); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_0RB0RB.nqhtr_1RB1LA_0LA1RC_1LB1RD_0RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_1LA0RB *)
Definition r_SPB_12_0017 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t1LA;t0RB].
Lemma cv_SPB_12_0017 : coversTr (row_to_tm r_SPB_12_0017).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_1LA0RB.tm_1RB1LA_0LA1RC_1LB1RD_1LA0RB); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_1LA0RB.nqhtr_1RB1LA_0LA1RC_1LB1RD_1LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_1LC0RB *)
Definition r_SPB_12_0018 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t1LC;t0RB].
Lemma cv_SPB_12_0018 : coversTr (row_to_tm r_SPB_12_0018).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_1LC0RB.tm_1RB1LA_0LA1RC_1LB1RD_1LC0RB); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_1LC0RB.nqhtr_1RB1LA_0LA1RC_1LB1RD_1LC0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LB1RD_1RB0RB *)
Definition r_SPB_12_0019 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LB;t1RD;t1RB;t0RB].
Lemma cv_SPB_12_0019 : coversTr (row_to_tm r_SPB_12_0019).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LB1RD_1RB0RB.tm_1RB1LA_0LA1RC_1LB1RD_1RB0RB); [exact LAPT_1RB1LA_0LA1RC_1LB1RD_1RB0RB.nqhtr_1RB1LA_0LA1RC_1LB1RD_1RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_0LA0RB *)
Definition r_SPB_12_0020 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t0LA;t0RB].
Lemma cv_SPB_12_0020 : coversTr (row_to_tm r_SPB_12_0020).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_0LA0RB.tm_1RB1LA_0LA1RC_1LC1RD_0LA0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_0LA0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_0LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_0LB0RB *)
Definition r_SPB_12_0021 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t0LB;t0RB].
Lemma cv_SPB_12_0021 : coversTr (row_to_tm r_SPB_12_0021).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_0LB0RB.tm_1RB1LA_0LA1RC_1LC1RD_0LB0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_0LB0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_0LB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_0LD0RB *)
Definition r_SPB_12_0022 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t0LD;t0RB].
Lemma cv_SPB_12_0022 : coversTr (row_to_tm r_SPB_12_0022).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_0LD0RB.tm_1RB1LA_0LA1RC_1LC1RD_0LD0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_0LD0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_0LD0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_0RB0LC *)
Definition r_SPB_12_0023 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t0RB;t0LC].
Lemma cv_SPB_12_0023 : coversTr (row_to_tm r_SPB_12_0023).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_0RB0LC.tm_1RB1LA_0LA1RC_1LC1RD_0RB0LC); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_0RB0LC.nqhtr_1RB1LA_0LA1RC_1LC1RD_0RB0LC | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_0RB0RB *)
Definition r_SPB_12_0024 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t0RB;t0RB].
Lemma cv_SPB_12_0024 : coversTr (row_to_tm r_SPB_12_0024).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_0RB0RB.tm_1RB1LA_0LA1RC_1LC1RD_0RB0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_0RB0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_0RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_1LA0RB *)
Definition r_SPB_12_0025 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t1LA;t0RB].
Lemma cv_SPB_12_0025 : coversTr (row_to_tm r_SPB_12_0025).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_1LA0RB.tm_1RB1LA_0LA1RC_1LC1RD_1LA0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_1LA0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_1LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_1LC0RB *)
Definition r_SPB_12_0026 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t1LC;t0RB].
Lemma cv_SPB_12_0026 : coversTr (row_to_tm r_SPB_12_0026).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_1LC0RB.tm_1RB1LA_0LA1RC_1LC1RD_1LC0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_1LC0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_1LC0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1LC1RD_1RB0RB *)
Definition r_SPB_12_0027 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1LC;t1RD;t1RB;t0RB].
Lemma cv_SPB_12_0027 : coversTr (row_to_tm r_SPB_12_0027).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1LC1RD_1RB0RB.tm_1RB1LA_0LA1RC_1LC1RD_1RB0RB); [exact LAPT_1RB1LA_0LA1RC_1LC1RD_1RB0RB.nqhtr_1RB1LA_0LA1RC_1LC1RD_1RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RA1RD_---0RB *)
Definition r_SPB_12_0028 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RA;t1RD;tN;t0RB].
Lemma cv_SPB_12_0028 : coversTr (row_to_tm r_SPB_12_0028).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RA1RD____0RB.tm_1RB1LA_0LA1RC_1RA1RD____0RB); [exact LAPT_1RB1LA_0LA1RC_1RA1RD____0RB.nqhtr_1RB1LA_0LA1RC_1RA1RD____0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RA1RD_0RB0LC *)
Definition r_SPB_12_0029 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RA;t1RD;t0RB;t0LC].
Lemma cv_SPB_12_0029 : coversTr (row_to_tm r_SPB_12_0029).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RA1RD_0RB0LC.tm_1RB1LA_0LA1RC_1RA1RD_0RB0LC); [exact LAPT_1RB1LA_0LA1RC_1RA1RD_0RB0LC.nqhtr_1RB1LA_0LA1RC_1RA1RD_0RB0LC | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB0RB_------ *)
Definition r_SPB_12_0030 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t0RB;tN;tN].
Lemma cv_SPB_12_0030 : coversTr (row_to_tm r_SPB_12_0030).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB0RB_______.tm_1RB1LA_0LA1RC_1RB0RB_______); [exact LAPT_1RB1LA_0LA1RC_1RB0RB_______.nqhtr_1RB1LA_0LA1RC_1RB0RB_______ | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_0LA0RB *)
Definition r_SPB_12_0031 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t0LA;t0RB].
Lemma cv_SPB_12_0031 : coversTr (row_to_tm r_SPB_12_0031).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_0LA0RB.tm_1RB1LA_0LA1RC_1RB1RD_0LA0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_0LA0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_0LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_0LB0RB *)
Definition r_SPB_12_0032 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t0LB;t0RB].
Lemma cv_SPB_12_0032 : coversTr (row_to_tm r_SPB_12_0032).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_0LB0RB.tm_1RB1LA_0LA1RC_1RB1RD_0LB0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_0LB0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_0LB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_0LD0RB *)
Definition r_SPB_12_0033 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t0LD;t0RB].
Lemma cv_SPB_12_0033 : coversTr (row_to_tm r_SPB_12_0033).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_0LD0RB.tm_1RB1LA_0LA1RC_1RB1RD_0LD0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_0LD0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_0LD0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_0RB0LC *)
Definition r_SPB_12_0034 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t0RB;t0LC].
Lemma cv_SPB_12_0034 : coversTr (row_to_tm r_SPB_12_0034).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_0RB0LC.tm_1RB1LA_0LA1RC_1RB1RD_0RB0LC); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_0RB0LC.nqhtr_1RB1LA_0LA1RC_1RB1RD_0RB0LC | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_0RB0RB *)
Definition r_SPB_12_0035 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t0RB;t0RB].
Lemma cv_SPB_12_0035 : coversTr (row_to_tm r_SPB_12_0035).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_0RB0RB.tm_1RB1LA_0LA1RC_1RB1RD_0RB0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_0RB0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_0RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_1LA0RB *)
Definition r_SPB_12_0036 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t1LA;t0RB].
Lemma cv_SPB_12_0036 : coversTr (row_to_tm r_SPB_12_0036).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_1LA0RB.tm_1RB1LA_0LA1RC_1RB1RD_1LA0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_1LA0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_1LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_1LC0RB *)
Definition r_SPB_12_0037 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t1LC;t0RB].
Lemma cv_SPB_12_0037 : coversTr (row_to_tm r_SPB_12_0037).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_1LC0RB.tm_1RB1LA_0LA1RC_1RB1RD_1LC0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_1LC0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_1LC0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RB1RD_1RB0RB *)
Definition r_SPB_12_0038 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RB;t1RD;t1RB;t0RB].
Lemma cv_SPB_12_0038 : coversTr (row_to_tm r_SPB_12_0038).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RB1RD_1RB0RB.tm_1RB1LA_0LA1RC_1RB1RD_1RB0RB); [exact LAPT_1RB1LA_0LA1RC_1RB1RD_1RB0RB.nqhtr_1RB1LA_0LA1RC_1RB1RD_1RB0RB | intros q s; destruct q, s; reflexivity]. Qed.

(* spec 1RB1LA_0LA1RC_1RD0LB_0LA0RB *)
Definition r_SPB_12_0039 : list (option Trans) := [t1RB;t1LA;t0LA;t1RC;t1RD;t0LB;t0LA;t0RB].
Lemma cv_SPB_12_0039 : coversTr (row_to_tm r_SPB_12_0039).
Proof. apply (coversTr_nqh_at LAPT_1RB1LA_0LA1RC_1RD0LB_0LA0RB.tm_1RB1LA_0LA1RC_1RD0LB_0LA0RB); [exact LAPT_1RB1LA_0LA1RC_1RD0LB_0LA0RB.nqhtr_1RB1LA_0LA1RC_1RD0LB_0LA0RB | intros q s; destruct q, s; reflexivity]. Qed.

Definition cbtrows_SPB_12 : list (list (option Trans)) :=
  [r_SPB_12_0000;
   r_SPB_12_0001;
   r_SPB_12_0002;
   r_SPB_12_0003;
   r_SPB_12_0004;
   r_SPB_12_0005;
   r_SPB_12_0006;
   r_SPB_12_0007;
   r_SPB_12_0008;
   r_SPB_12_0009;
   r_SPB_12_0010;
   r_SPB_12_0011;
   r_SPB_12_0012;
   r_SPB_12_0013;
   r_SPB_12_0014;
   r_SPB_12_0015;
   r_SPB_12_0016;
   r_SPB_12_0017;
   r_SPB_12_0018;
   r_SPB_12_0019;
   r_SPB_12_0020;
   r_SPB_12_0021;
   r_SPB_12_0022;
   r_SPB_12_0023;
   r_SPB_12_0024;
   r_SPB_12_0025;
   r_SPB_12_0026;
   r_SPB_12_0027;
   r_SPB_12_0028;
   r_SPB_12_0029;
   r_SPB_12_0030;
   r_SPB_12_0031;
   r_SPB_12_0032;
   r_SPB_12_0033;
   r_SPB_12_0034;
   r_SPB_12_0035;
   r_SPB_12_0036;
   r_SPB_12_0037;
   r_SPB_12_0038;
   r_SPB_12_0039].

Lemma cbt_SPB_12_covers : Forall coversTr (map row_to_tm cbtrows_SPB_12).
Proof. exact (Forall_cons _ cv_SPB_12_0000 (Forall_cons _ cv_SPB_12_0001 (Forall_cons _ cv_SPB_12_0002 (Forall_cons _ cv_SPB_12_0003 (Forall_cons _ cv_SPB_12_0004 (Forall_cons _ cv_SPB_12_0005 (Forall_cons _ cv_SPB_12_0006 (Forall_cons _ cv_SPB_12_0007 (Forall_cons _ cv_SPB_12_0008 (Forall_cons _ cv_SPB_12_0009 (Forall_cons _ cv_SPB_12_0010 (Forall_cons _ cv_SPB_12_0011 (Forall_cons _ cv_SPB_12_0012 (Forall_cons _ cv_SPB_12_0013 (Forall_cons _ cv_SPB_12_0014 (Forall_cons _ cv_SPB_12_0015 (Forall_cons _ cv_SPB_12_0016 (Forall_cons _ cv_SPB_12_0017 (Forall_cons _ cv_SPB_12_0018 (Forall_cons _ cv_SPB_12_0019 (Forall_cons _ cv_SPB_12_0020 (Forall_cons _ cv_SPB_12_0021 (Forall_cons _ cv_SPB_12_0022 (Forall_cons _ cv_SPB_12_0023 (Forall_cons _ cv_SPB_12_0024 (Forall_cons _ cv_SPB_12_0025 (Forall_cons _ cv_SPB_12_0026 (Forall_cons _ cv_SPB_12_0027 (Forall_cons _ cv_SPB_12_0028 (Forall_cons _ cv_SPB_12_0029 (Forall_cons _ cv_SPB_12_0030 (Forall_cons _ cv_SPB_12_0031 (Forall_cons _ cv_SPB_12_0032 (Forall_cons _ cv_SPB_12_0033 (Forall_cons _ cv_SPB_12_0034 (Forall_cons _ cv_SPB_12_0035 (Forall_cons _ cv_SPB_12_0036 (Forall_cons _ cv_SPB_12_0037 (Forall_cons _ cv_SPB_12_0038 (Forall_cons _ cv_SPB_12_0039 (Forall_nil _))))))))))))))))))))))))))))))))))))))))). Qed.
