(** GENERATED by tools/censustr/gen_provtr_rw.py split -- DO NOT EDIT.
    Independent RepWL checks for stage 11, part 040. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.CensusTr Require Import RepWLTr.
Import ListNotations.

(* 1RB0LA_0RC1RD_1LC1LA_0RB1RB  L=10 T=2 t=0 fuel=107400 M=42 *)
Definition tm_rw11_0085 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StA)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StD)
  | StC, S0 => Some (mkTrans S1 DL StC)
  | StC, S1 => Some (mkTrans S1 DL StA)
  | StD, S0 => Some (mkTrans S0 DR StB)
  | StD, S1 => Some (mkTrans S1 DR StB)
  end.
Lemma nqhtr_rw11_0085 : NeverQuasiHaltsTr tm_rw11_0085.
Proof. apply (rw_tier_tr_sound _ 10 2 0 107400 42). vm_cast_no_check (eq_refl true). Qed.

Definition ptw_11_p040 : list TM :=
  [tm_rw11_0085].

Lemma ptw_11_p040_nqhtr : Forall NeverQuasiHaltsTr ptw_11_p040.
Proof. exact (Forall_cons _ nqhtr_rw11_0085 (Forall_nil NeverQuasiHaltsTr)). Qed.
