(** GENERATED by tools/censustr/gen_provtr_rw.py split -- DO NOT EDIT.
    Independent RepWL checks for stage 10, part 016. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.CensusTr Require Import RepWLTr.
Import ListNotations.

(* 1RB0LC_1LA0RD_0RB0LB_1RA0RD  L=6 T=2 t=0 fuel=100000 M=128 *)
Definition tm_rw10_0016 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S1 DL StA)
  | StB, S1 => Some (mkTrans S0 DR StD)
  | StC, S0 => Some (mkTrans S0 DR StB)
  | StC, S1 => Some (mkTrans S0 DL StB)
  | StD, S0 => Some (mkTrans S1 DR StA)
  | StD, S1 => Some (mkTrans S0 DR StD)
  end.
Lemma nqhtr_rw10_0016 : NeverQuasiHaltsTr tm_rw10_0016.
Proof. apply (rw_tier_tr_sound _ 6 2 0 100000 128). vm_cast_no_check (eq_refl true). Qed.

Definition ptw_10_p016 : list TM :=
  [tm_rw10_0016].

Lemma ptw_10_p016_nqhtr : Forall NeverQuasiHaltsTr ptw_10_p016.
Proof. exact (Forall_cons _ nqhtr_rw10_0016 (Forall_nil NeverQuasiHaltsTr)). Qed.
