(** GENERATED by tools/censustr/gen_provtr_rw.py split -- DO NOT EDIT.
    Independent RepWL checks for stage 11, part 026. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.CensusTr Require Import RepWLTr.
Import ListNotations.

(* 0RB1RA_1LC0RD_1LD1LB_1RA0LC  L=7 T=2 t=0 fuel=118440 M=37 *)
Definition tm_rw11_0060 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S0 DR StB)
  | StA, S1 => Some (mkTrans S1 DR StA)
  | StB, S0 => Some (mkTrans S1 DL StC)
  | StB, S1 => Some (mkTrans S0 DR StD)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S1 DL StB)
  | StD, S0 => Some (mkTrans S1 DR StA)
  | StD, S1 => Some (mkTrans S0 DL StC)
  end.
Lemma nqhtr_rw11_0060 : NeverQuasiHaltsTr tm_rw11_0060.
Proof. apply (rw_tier_tr_sound _ 7 2 0 118440 37). vm_cast_no_check (eq_refl true). Qed.

Definition ptw_11_p026 : list TM :=
  [tm_rw11_0060].

Lemma ptw_11_p026_nqhtr : Forall NeverQuasiHaltsTr ptw_11_p026.
Proof. exact (Forall_cons _ nqhtr_rw11_0060 (Forall_nil NeverQuasiHaltsTr)). Qed.
