(** GENERATED by tools/censustr/gen_provtr_rw.py split -- DO NOT EDIT.
    Independent RepWL checks for stage 03, part 014. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.CensusTr Require Import RepWLTr.
Import ListNotations.

(* 1RB0LC_0RC1RA_1LD0RA_1LA0LC  L=5 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0073 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StA)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S0 DR StA)
  | StD, S0 => Some (mkTrans S1 DL StA)
  | StD, S1 => Some (mkTrans S0 DL StC)
  end.
Lemma nqhtr_rw03_0073 : NeverQuasiHaltsTr tm_rw03_0073.
Proof. apply (rw_tier_tr_sound _ 5 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RA_1LD1RB_0LA1LD  L=7 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0074 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StA)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S1 DR StB)
  | StD, S0 => Some (mkTrans S0 DL StA)
  | StD, S1 => Some (mkTrans S1 DL StD)
  end.
Lemma nqhtr_rw03_0074 : NeverQuasiHaltsTr tm_rw03_0074.
Proof. apply (rw_tier_tr_sound _ 7 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RA_1LD1RB_1LA1LD  L=5 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0075 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StA)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S1 DR StB)
  | StD, S0 => Some (mkTrans S1 DL StA)
  | StD, S1 => Some (mkTrans S1 DL StD)
  end.
Lemma nqhtr_rw03_0075 : NeverQuasiHaltsTr tm_rw03_0075.
Proof. apply (rw_tier_tr_sound _ 5 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RB_1LD0RB_0LA1LA  L=8 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0076 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StB)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S0 DR StB)
  | StD, S0 => Some (mkTrans S0 DL StA)
  | StD, S1 => Some (mkTrans S1 DL StA)
  end.
Lemma nqhtr_rw03_0076 : NeverQuasiHaltsTr tm_rw03_0076.
Proof. apply (rw_tier_tr_sound _ 8 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RB_1LD0RB_0LA1RB  L=7 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0077 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StB)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S0 DR StB)
  | StD, S0 => Some (mkTrans S0 DL StA)
  | StD, S1 => Some (mkTrans S1 DR StB)
  end.
Lemma nqhtr_rw03_0077 : NeverQuasiHaltsTr tm_rw03_0077.
Proof. apply (rw_tier_tr_sound _ 7 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RC_0LD1RB_1LA0RB  L=5 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0078 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StC)
  | StC, S0 => Some (mkTrans S0 DL StD)
  | StC, S1 => Some (mkTrans S1 DR StB)
  | StD, S0 => Some (mkTrans S1 DL StA)
  | StD, S1 => Some (mkTrans S0 DR StB)
  end.
Lemma nqhtr_rw03_0078 : NeverQuasiHaltsTr tm_rw03_0078.
Proof. apply (rw_tier_tr_sound _ 5 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RC_1LD0RA_1LA0LA  L=6 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0079 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StC)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S0 DR StA)
  | StD, S0 => Some (mkTrans S1 DL StA)
  | StD, S1 => Some (mkTrans S0 DL StA)
  end.
Lemma nqhtr_rw03_0079 : NeverQuasiHaltsTr tm_rw03_0079.
Proof. apply (rw_tier_tr_sound _ 6 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RD_1LA1LC_0LC0RB  L=8 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0080 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StD)
  | StC, S0 => Some (mkTrans S1 DL StA)
  | StC, S1 => Some (mkTrans S1 DL StC)
  | StD, S0 => Some (mkTrans S0 DL StC)
  | StD, S1 => Some (mkTrans S0 DR StB)
  end.
Lemma nqhtr_rw03_0080 : NeverQuasiHaltsTr tm_rw03_0080.
Proof. apply (rw_tier_tr_sound _ 8 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RD_1LA1LC_1LC0RB  L=8 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0081 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StD)
  | StC, S0 => Some (mkTrans S1 DL StA)
  | StC, S1 => Some (mkTrans S1 DL StC)
  | StD, S0 => Some (mkTrans S1 DL StC)
  | StD, S1 => Some (mkTrans S0 DR StB)
  end.
Lemma nqhtr_rw03_0081 : NeverQuasiHaltsTr tm_rw03_0081.
Proof. apply (rw_tier_tr_sound _ 8 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

(* 1RB0LC_0RC1RD_1LD0RA_1LA0LC  L=5 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw03_0082 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S1 DR StB)
  | StA, S1 => Some (mkTrans S0 DL StC)
  | StB, S0 => Some (mkTrans S0 DR StC)
  | StB, S1 => Some (mkTrans S1 DR StD)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S0 DR StA)
  | StD, S0 => Some (mkTrans S1 DL StA)
  | StD, S1 => Some (mkTrans S0 DL StC)
  end.
Lemma nqhtr_rw03_0082 : NeverQuasiHaltsTr tm_rw03_0082.
Proof. apply (rw_tier_tr_sound _ 5 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

Definition ptw_03_p014 : list TM :=
  [tm_rw03_0073;
   tm_rw03_0074;
   tm_rw03_0075;
   tm_rw03_0076;
   tm_rw03_0077;
   tm_rw03_0078;
   tm_rw03_0079;
   tm_rw03_0080;
   tm_rw03_0081;
   tm_rw03_0082].

Lemma ptw_03_p014_nqhtr : Forall NeverQuasiHaltsTr ptw_03_p014.
Proof. exact (Forall_cons _ nqhtr_rw03_0073 (Forall_cons _ nqhtr_rw03_0074 (Forall_cons _ nqhtr_rw03_0075 (Forall_cons _ nqhtr_rw03_0076 (Forall_cons _ nqhtr_rw03_0077 (Forall_cons _ nqhtr_rw03_0078 (Forall_cons _ nqhtr_rw03_0079 (Forall_cons _ nqhtr_rw03_0080 (Forall_cons _ nqhtr_rw03_0081 (Forall_cons _ nqhtr_rw03_0082 (Forall_nil NeverQuasiHaltsTr))))))))))). Qed.
