(** GENERATED by tools/censustr/gen_provtr_rw.py split -- DO NOT EDIT.
    Independent RepWL checks for stage 01, part 000. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.CensusTr Require Import RepWLTr.
Import ListNotations.

(* 0RB0RA_1LC0RC_0LD1RA_1RA0LB  L=9 T=2 t=0 fuel=30000 M=32 *)
Definition tm_rw01_0000 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S0 DR StB)
  | StA, S1 => Some (mkTrans S0 DR StA)
  | StB, S0 => Some (mkTrans S1 DL StC)
  | StB, S1 => Some (mkTrans S0 DR StC)
  | StC, S0 => Some (mkTrans S0 DL StD)
  | StC, S1 => Some (mkTrans S1 DR StA)
  | StD, S0 => Some (mkTrans S1 DR StA)
  | StD, S1 => Some (mkTrans S0 DL StB)
  end.
Lemma nqhtr_rw01_0000 : NeverQuasiHaltsTr tm_rw01_0000.
Proof. apply (rw_tier_tr_sound _ 9 2 0 30000 32). vm_cast_no_check (eq_refl true). Qed.

Definition ptw_01_p000 : list TM :=
  [tm_rw01_0000].

Lemma ptw_01_p000_nqhtr : Forall NeverQuasiHaltsTr ptw_01_p000.
Proof. exact (Forall_cons _ nqhtr_rw01_0000 (Forall_nil NeverQuasiHaltsTr)). Qed.
