(** GENERATED by tools/censustr/gen_provtr_rw.py split -- DO NOT EDIT.
    Independent RepWL checks for stage 14, part 027. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement BBBT4_Statement.
From BBB4.CensusTr Require Import RepWLTr.
Import ListNotations.

(* 0RB0RA_1LC1RA_1LD1RD_1RD0LB  L=15 T=2 t=0 fuel=133464 M=60 *)
Definition tm_rw14_0062 : TM := fun q s =>
  match q, s with
  | StA, S0 => Some (mkTrans S0 DR StB)
  | StA, S1 => Some (mkTrans S0 DR StA)
  | StB, S0 => Some (mkTrans S1 DL StC)
  | StB, S1 => Some (mkTrans S1 DR StA)
  | StC, S0 => Some (mkTrans S1 DL StD)
  | StC, S1 => Some (mkTrans S1 DR StD)
  | StD, S0 => Some (mkTrans S1 DR StD)
  | StD, S1 => Some (mkTrans S0 DL StB)
  end.
Lemma nqhtr_rw14_0062 : NeverQuasiHaltsTr tm_rw14_0062.
Proof. apply (rw_tier_tr_sound _ 15 2 0 133464 60). vm_cast_no_check (eq_refl true). Qed.

Definition ptw_14_p027 : list TM :=
  [tm_rw14_0062].

Lemma ptw_14_p027_nqhtr : Forall NeverQuasiHaltsTr ptw_14_p027.
Proof. exact (Forall_cons _ nqhtr_rw14_0062 (Forall_nil NeverQuasiHaltsTr)). Qed.
