exec(open("/tmp/claude-0/-home-user/879c13c5-822c-53a0-bc9c-dd6a0e06b6ca/scratchpad/lexproto.py").read().split("sample=mirror")[0])
tbl=mirror(parse("1RB1LD_1LC0LD_1RC1RA_0LB0RA"))
n=2
seen,lset,rset=build_closure(tbl,n,0)
def cq(a):
    q,s,lw,rw=a
    sym=lambda v:"S1" if v==1 else "S0"
    return "(St%s, ([%s], %s, [%s]))"%(chr(65+q),"; ".join(sym(v) for v in lw),sym(s),"; ".join(sym(v) for v in rw))
def emit_phi(phi):
    return "[" + ";\n   ".join("(%s, %d)"%(cq(a),v) for a,v in sorted(phi.items(), key=str) if v!=0) + "]"
out=[]
out.append("(** Generated by tools/gen_lex_cert.py from the BBB harness's rank\n    procedure (rules a/b) on the n=2 n-gram closure of the mirrored\n    README sample machine.  Data only; the checker re-verifies. *)\n")
out.append("From Coq Require Import List.\nFrom BBB4 Require Import BBB4_Statement CTape.\nFrom BBB4.Checkers Require Import NGram.\nImport ListNotations.\n")
mn=["MAll","MLeft","MRight"]
for qq in range(4):
    comps=procedure(tbl,seen,lset,rset,qq)
    ok,bad=lex_check(tbl,seen,lset,rset,qq,comps,len(seen)+2)
    assert ok, (qq,bad)
    items=[]
    for comp in comps:
        if comp[0]=="rank":
            items.append("NgRank\n  %s"%emit_phi(comp[1]))
        else:
            _,mid,K,phi,gate=comp
            g="[" + ";\n   ".join(cq(a) for a in sorted(gate,key=str)) + "]"
            items.append("NgMeas %s %d\n  %s\n  %s"%(mn[mid],K,emit_phi(phi),g))
    out.append("Definition cert_%s : list ngcomp := [\n%s].\n"%(chr(65+qq),";\n".join(items)))
out.append("""Definition sample_cert (q : St) : list ngcomp :=
  match q with
  | StA => cert_A | StB => cert_B | StC => cert_C | StD => cert_D
  end.""")
open("theories/Machines/Sample_LexCert.v","w").write("\n".join(out)+"\n")
print("emitted", sum(len(x) for x in out), "chars")
