#!/usr/bin/env python3
"""Make the census walk units LEAN: each keeps only its [_empty] lemma
and Requires the computational half of the census, never the boards.

A walk unit is two lemmas of wildly different cost:

  X_empty   : Nat.iter 700 q_suc (q_..sub ...) = ([], [])   <- minutes
  X_decided : NodeDecided B_census D_census (node_tm ...)    <- an [exact]

They shared a file, so the file's environment was the union of what both
need -- and [X_decided] needs [decider_WF], hence [proven_all], hence
every boarded machine.  Measured (docs/CENSUS_RUNTIME.md): 5.32 GB and
25 s per unit natively, before deciding anything, times 154 files.

This moves each [_decided] up into the file that already imports the
unit and already loads the full environment (its layer's assembler), and
repoints the unit at Census/Run_Compute.v.  The assembler then pays that
environment ONCE per layer instead of once per unit.  Nothing else moves:
same lemma names, same statements, same proofs, same assembly.

It also lifts the [tm_g_* / ggchild_* / q_ggsub_*] definitions out of the
seven Census/Run_Split_<tag>.v into Census/Run_Compute_Split.v, for the
same reason Run_Split2's roots moved to Run_Compute: a unit names one of
them and must not drag the lemmas in with it.

Idempotent: re-running on an already-lean tree is a no-op.

Usage: lean_walk_units.py [--dry-run]

Untrusted build wiring.  Everything it produces is re-checked by the
kernel, and a mis-wire is a compile error, not a silent hole: an
assembler that loses a [_decided] cannot prove its own.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CENSUS = os.path.join(ROOT, 'theories', 'Census')
COMPUTE = os.path.join(CENSUS, 'Compute')

LEAN_REQ = ("From BBB4.Census Require Import TNF_QH Decide Run_Compute\n"
            "                                Run_Compute_Split.\n")
REQ_RE = re.compile(
    r'^From BBB4\.Census Require Import [^.]*\.\n'
    r'(?:^From BBB4\.Census Require Import [^.]*\.\n)*', re.M)
DECIDED_RE = re.compile(
    r'\nLemma (\w+_decided)\s*:.*?\nQed\.\n', re.S)
DEF_RE = re.compile(
    r'^Definition (tm_g_\w+|ggchild_\w+|q_ggsub_\w+)\b.*?\n\n', re.M | re.S)


def modname(path):
    return os.path.basename(path)[:-2]


def parents():
    """unit module name -> the .v that Require Imports it."""
    out = {}
    for p in glob.glob(os.path.join(CENSUS, '**', '*.v'), recursive=True):
        txt = open(p).read()
        for m in re.findall(r'From BBB4\.Census\.Compute Require Import '
                            r'(\w+)\.', txt):
            out.setdefault(m, p)
    return out


def lift_split_defs(dry):
    """the 7 Run_Split_<tag>.v roots -> Run_Compute_Split.v"""
    blocks, touched = [], []
    for p in sorted(glob.glob(os.path.join(CENSUS, 'Run_Split_*.v'))):
        txt = open(p).read()
        found = DEF_RE.findall(txt)
        if not found:
            continue
        tag = modname(p).replace('Run_Split_', '')
        keep = []
        for m in DEF_RE.finditer(txt):
            keep.append(m.group(0).rstrip() + "\n")
        blocks.append(f"\n(** the heavy grandchild A0/B0 = {tag} *)\n"
                      + "\n".join(keep))
        txt = DEF_RE.sub('', txt)
        txt = txt.replace(
            "From BBB4.Census Require Import TNF_QH Decide Deferred_Data "
            "Run Run_Split.\n",
            "From BBB4.Census Require Import TNF_QH Decide Deferred_Data "
            "Run Run_Split.\n"
            "(** its root definitions live in Run_Compute_Split.v so the\n"
            "    GGH_ units can name them without loading the boards. *)\n"
            "From BBB4.Census Require Import Run_Compute_Split.\n", 1)
        touched.append(p)
        if not dry:
            open(p, 'w').write(txt)
    if blocks and not dry:
        with open(os.path.join(CENSUS, 'Run_Compute_Split.v'), 'w') as f:
            f.write('''(** * Census/Run_Compute_Split: the heavy-grandchild roots.

    GENERATED by tools/lean_walk_units.py -- do not edit.

    The [tm_g_* / ggchild_* / q_ggsub_*] of the seven
    Census/Run_Split_<tag>.v, moved here for the reason Run_Split2's
    roots moved to Run_Compute: a GGH_ walk unit names one of them, and
    if it had to Require the file that PROVES things about them it would
    load Run.v, Proven_Data.v and every board with it -- 5.32 GB and
    25 s, natively, before deciding a machine.

    Definitions only.  The WF and [_decided] lemmas stay in their
    Run_Split_<tag>.v. *)

From Coq Require Import Arith Bool List.
From BBB4 Require Import BBB4_Statement.
From BBB4.Census Require Import TNF_QH Decide Run_Compute.
Import ListNotations.
''' + "".join(blocks))
    return touched


def main():
    dry = '--dry-run' in sys.argv
    par = parents()
    lifted = lift_split_defs(dry)
    moved, lean = 0, 0
    pending = {}                      # parent path -> [lemma text]
    for p in sorted(glob.glob(os.path.join(COMPUTE, '*.v'))):
        name = modname(p)
        if name == 'Census_Theorem':
            continue
        txt = open(p).read()
        if '_empty' not in txt:       # pure assembler, leave it
            continue
        m = DECIDED_RE.search(txt)
        if m:
            parent = par.get(name)
            if not parent:
                sys.exit(f"{name}: no file imports it -- cannot move "
                         f"{m.group(1)}")
            pending.setdefault(parent, []).append(m.group(0))
            txt = txt[:m.start()] + txt[m.end():]
            moved += 1
        new = REQ_RE.sub(LEAN_REQ, txt, count=1)
        if new != txt or m:
            lean += 1
            if not dry:
                open(p, 'w').write(new)
    for parent, lemmas in pending.items():
        txt = open(parent).read()
        anchor = 'Import ListNotations.\n'
        i = txt.index(anchor) + len(anchor)
        add = ("\n(** the per-unit [_decided] steps, moved here by\n"
               "    tools/lean_walk_units.py: each is an [exact] that takes\n"
               "    milliseconds but needs [decider_WF], and this file\n"
               "    already loads the environment that supplies it. *)\n"
               + "".join(lemmas))
        if not dry:
            open(parent, 'w').write(txt[:i] + add + txt[i:])
    print(f"{'(dry run) ' if dry else ''}units made lean: {lean}, "
          f"_decided lemmas moved: {moved}, "
          f"Run_Split_<tag> files lifted: {len(lifted)}, "
          f"assemblers updated: {len(pending)}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
