#!/usr/bin/env python3
"""Wire the STAGED wave-2 + wave-3 residue proofs into the census tier
inputs and regenerate Deferred_* (UNTRUSTED tooling; BOX FOLLOW-UP).

!!! This EDITS CENSUS .v INPUTS (RerootQH_Data.v, Proven_Data.v,
Deferred_*) -- run it ONLY on stable hardware, after the currently
running census re-cert has landed, and follow with `make census-verify`
+ `census_cache.py --update`.  It refuses to run without --box. !!!

What it wires (docs/REROOT_LISTC_STAGE.md + docs/IRULESQH_WAVE3.md):

  wave-2 track 1 (R_QH):      Machines/RerootStage/RRStage_00..15
                              (1,518) -> reroot_qh_list
  wave-2 track 2 (R_NeverQH): Machines/ListCStage/LCStage_00..11
                              (591)  -> proven_list
  wave-3 (R_QH):              Machines/IRulesQHStage/IQHStage_*
                              -> reroot_qh_list

Steps:
  1. rewrite theories/Census/RerootQH_Data.v: import + append the
     RRStage and IQHStage lists, extend the Forall_app chain
     (rrqh / iqh are definitionally the tier predicate).
  2. rewrite theories/Census/Proven_Data.v: import + append the
     LCStage lists, extend the Forall_app chain.
  3. drop lists:
       append RRStage machines to tools/reroot_boarded.txt (184->1,702);
       write tools/proven_listc_dropped.txt from listc_stage_manifest;
       write tools/iqh_boarded.txt from irulesqh manifest.
  4. add the staged modules to _CoqProject (marked block).
  5. run regen_residue.py --wave3 (all set asserts live there).

After it: `make census-verify` on the box, Print Assumptions
census_decided must stay functional_extensionality_dep only, then
census_cache.py --update and commit the census .vo + hash.

Usage: wire_wave3.py --box
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CENSUS = os.path.join(ROOT, "theories", "Census")

# regen_residue.py's stage 1 rebuilds the PRE-SHRINK deferred set from
# scratch and therefore needs the FULL 3,713-machine BBB4 holdout list --
# NOT tools/census_holdouts_kept.txt, which regen itself overwrites with
# the currently-kept holdouts (e.g. 27 after the provenqh wire) and which
# therefore fails the len==3713 assert on any already-shrunk tree.
# The list is VENDORED (byte-identical copy of the BBB harness's
# BBB4_holdouts_3713.txt) so wiring needs no sibling checkout; set
# BBB_REPO to prefer an upstream checkout's copy instead.
HOLDOUTS_3713 = os.path.join(HERE, "BBB4_holdouts_3713.txt")
if "BBB_REPO" in os.environ:
    HOLDOUTS_3713 = os.path.join(os.environ["BBB_REPO"],
                                 "BBB4_holdouts_3713.txt")


def staged_files(subdir, prefix):
    d = os.path.join(ROOT, "theories", "Machines", subdir)
    if not os.path.isdir(d):
        return []
    return sorted(f[:-2] for f in os.listdir(d)
                  if f.startswith(prefix) and f.endswith(".v"))


def manifest_machines(path, expect_min=1):
    with open(path) as f:
        head = next(f)
        assert head.startswith("machine\t"), (path, head)
        ms = [l.split("\t")[0] for l in f if l.strip()]
    assert len(ms) >= expect_min, (path, len(ms))
    assert len(set(ms)) == len(ms), (path, "duplicate machines")
    return ms


def rewrite_rerootqh_data(rr, iqh):
    """RerootQH_Data.v: base rerootqh_00..04 + RRStage + IQHStage."""
    path = os.path.join(CENSUS, "RerootQH_Data.v")
    base = ["rerootqh_%02d" % i for i in range(5)]
    rr_lists = [m.replace("RRStage_", "rrstage_") for m in rr]
    iqh_lists = [m.replace("IQHStage_", "iqhstage_") for m in iqh]
    all_lists = base + rr_lists + iqh_lists
    all_certs = (["%s_all" % b for b in base]
                 + ["%s_all" % l for l in rr_lists]
                 + ["%s_all" % l for l in iqh_lists])
    lines = [
        "(** GENERATED by tools/gen_reroot.py, EXTENDED by "
        "tools/wire_wave3.py -- DO NOT EDIT.",
        "",
        "    The census R_QH lookup tier data: the wave-1 re-root boards",
        "    (rerootqh_00..04), the wave-2 staged re-root boards",
        "    (the Machines/RerootStage batches), and the wave-3 irules-QH",
        "    boards (Machines/IRulesQHStage/IQHStage_*, via",
        "    Checkers/IRules/MetaBlkPfxQH.v).  Composed with the",
        "    proven-QH tier (Run.v) as extra R_QH lookup members. *)",
        "From Coq Require Import List.",
        "From BBB4 Require Import BBB4_Statement.",
        "From BBB4.Census Require Import TNF_QH "
        + " ".join("RerootQH_%02d" % i for i in range(5)) + ".",
    ]
    if rr:
        lines.append("From BBB4.Machines.RerootStage Require Import "
                     + " ".join(rr) + ".")
    if iqh:
        lines.append("From BBB4.Machines.IRulesQHStage Require Import "
                     + " ".join(iqh) + ".")
    lines += [
        "Import ListNotations.",
        "",
        "Definition reroot_qh_list : list TM :=",
        "  " + " ++ ".join(all_lists) + ".",
        "",
        "Lemma reroot_qh_all :",
        "  Forall (fun tm => NonHalt tm /\\ QHBound 2000 tm /\\ "
        "QuasiHaltsSt tm)",
        "         reroot_qh_list.",
        "Proof.",
        "  unfold reroot_qh_list.",
    ]
    for c in all_certs[:-1]:
        lines.append("  apply Forall_app; split; [exact %s|]." % c)
    lines.append("  exact %s." % all_certs[-1])
    lines.append("Qed.")
    open(path, "w").write("\n".join(lines) + "\n")
    print("rewrote %s (%d lists)" % (path, len(all_lists)))


def rewrite_proven_data(lc, lcs2):
    """Proven_Data.v: base Proven_00..07 + LCStage + LCS2 lists."""
    path = os.path.join(CENSUS, "Proven_Data.v")
    src = open(path).read()
    base_lists = re.findall(r"proven_\d\d", src)
    base_lists = sorted(set(base_lists))
    lc_lists = ([m.replace("LCStage_", "lcstage_") for m in lc]
                + [m.replace("LCS2_", "lcs2_") for m in lcs2])
    all_lists = base_lists + lc_lists
    all_certs = (["%s_nqh" % b for b in base_lists]
                 + ["%s_nqh" % l for l in lc_lists])
    lines = [
        "(** GENERATED by tools/gen_proven.py, EXTENDED by "
        "tools/wire_wave3.py -- DO NOT EDIT.",
        "",
        "    The census proven (R_NeverQH) lookup tier data: the boarded",
        "    holdout theorems (Proven_00..07) plus the wave-2/3 staged",
        "    list-C never-QH boards",
        "    (the Machines/ListCStage and Machines/ListCStage2 batches). *)",
        "From Coq Require Import List.",
        "From BBB4 Require Import BBB4_Statement.",
        "From BBB4.Census Require Import "
        + " ".join("Proven_%02d" % i for i in range(len(base_lists)))
        + ".",
    ]
    if lc:
        lines.append("From BBB4.Machines.ListCStage Require Import "
                     + " ".join(lc) + ".")
    if lcs2:
        lines.append("From BBB4.Machines.ListCStage2 Require Import "
                     + " ".join(lcs2) + ".")
    lines += [
        "Import ListNotations.",
        "",
        "Definition proven_list : list TM :=",
        "  " + " ++ ".join(all_lists) + ".",
        "",
        "Lemma proven_all : Forall NeverQuasiHaltsSt proven_list.",
        "Proof.",
        "  unfold proven_list.",
    ]
    for c in all_certs[:-1]:
        lines.append("  apply Forall_app; split; [exact %s|]." % c)
    lines.append("  exact %s." % all_certs[-1])
    lines.append("Qed.")
    open(path, "w").write("\n".join(lines) + "\n")
    print("rewrote %s (%d lists)" % (path, len(all_lists)))


def extend_coqproject(rr, lc, lcs2, iqh):
    path = os.path.join(ROOT, "_CoqProject")
    src = open(path).read()
    marker = "# --- wave-2/3 staged residue proofs (wired) ---"
    if marker in src:
        print("_CoqProject already has the wired block; skipping")
        return
    block = [marker]
    block += ["theories/Machines/RerootStage/%s.v" % m for m in rr]
    block += ["theories/Machines/ListCStage/%s.v" % m for m in lc]
    block += ["theories/Machines/ListCStage2/%s.v" % m for m in lcs2]
    block += ["theories/Machines/IRulesQHStage/%s.v" % m for m in iqh]
    block += ["theories/Tests/RerootStage_Corruption.v",
              "theories/Tests/IRulesQH_Corruption.v"]
    open(path, "a").write("\n" + "\n".join(block) + "\n")
    print("extended _CoqProject (+%d files)" % (len(block) - 1))


def main():
    if "--box" not in sys.argv[1:]:
        sys.exit("REFUSING: this edits census .v inputs; run on stable "
                 "hardware with --box (see the module docstring)")

    rr = staged_files("RerootStage", "RRStage_")
    lc = staged_files("ListCStage", "LCStage_")
    lcs2 = staged_files("ListCStage2", "LCS2_")
    iqh = staged_files("IRulesQHStage", "IQHStage_")
    print("staged: %d RRStage, %d LCStage, %d LCS2, %d IQHStage"
          % (len(rr), len(lc), len(lcs2), len(iqh)))
    assert rr and lc and iqh, "a staged tier is missing"

    # drop lists (all asserts re-checked by regen_residue --wave3)
    rr_m = manifest_machines(os.path.join(HERE,
                                          "reroot_stage_manifest.tsv"), 1500)
    boarded_path = os.path.join(HERE, "reroot_boarded.txt")
    boarded = [l.strip() for l in open(boarded_path) if l.strip()]
    merged = boarded + [m for m in rr_m if m not in set(boarded)]
    assert len(merged) == len(set(merged))
    open(boarded_path, "w").write("\n".join(merged) + "\n")
    print("reroot_boarded.txt: %d -> %d" % (len(boarded), len(merged)))

    lc_m = manifest_machines(os.path.join(HERE,
                                          "listc_stage_manifest.tsv"), 500)
    if lcs2:
        lc_m = lc_m + manifest_machines(
            os.path.join(HERE, "irulesnqh_manifest.tsv"), 1)
    assert len(lc_m) == len(set(lc_m)), "listc drop overlap (wave2/wave3)"
    open(os.path.join(HERE, "proven_listc_dropped.txt"),
         "w").write("\n".join(lc_m) + "\n")
    print("proven_listc_dropped.txt: %d" % len(lc_m))

    iqh_m = manifest_machines(os.path.join(HERE,
                                           "irulesqh_manifest.tsv"), 100)
    open(os.path.join(HERE, "iqh_boarded.txt"),
         "w").write("\n".join(iqh_m) + "\n")
    print("iqh_boarded.txt: %d" % len(iqh_m))

    rewrite_rerootqh_data(rr, iqh)
    rewrite_proven_data(lc, lcs2)
    extend_coqproject(rr, lc, lcs2, iqh)

    if not os.path.exists(HOLDOUTS_3713):
        sys.exit("REFUSING: full holdout list not found at %s -- set "
                 "BBB_REPO to the BBB harness checkout" % HOLDOUTS_3713)
    subprocess.run(
        [sys.executable, os.path.join(HERE, "regen_residue.py"),
         HOLDOUTS_3713, CENSUS, "--wave3"],
        check=True)
    print("\nWIRED.  Now: make census-verify on the box; check "
          "Print Assumptions census_decided; census_cache.py --update; "
          "commit the census .vo + CENSUS_VO_HASH.")


if __name__ == "__main__":
    main()
