(** GENERATED by tools/gen_gsplit_heavy.py -- do not edit.
    Census subtree: A0=1RB, B0=0LC, StC1 = 0LA. *)
From Coq Require Import Arith List.
From BBB4 Require Import BBB4_Statement.
From BBB4.Census Require Import TNF_QH Decide Run_Compute
                                Run_Compute_Split.
Import ListNotations.

Lemma ggh_1RB_0LC_0LA_empty :
  Nat.iter 700 q_suc (q_ggsub_1RB_0LC S0 DL StA) = ([], []).
Proof.
  native_cast_no_check (eq_refl (@nil TNF_Node, @nil TNF_Node)).
Qed.
